In [1]:
import requests
import pandas as pd

# **Scrapping player data (Messi)**

In [2]:
url = "http://footballapi.eastus.azurecontainer.io:3000/players/search?q=messi&page=15"

In [3]:
response = requests.get(url)
data = response.json()

In [4]:
print(data)

[{'entity': {'id': 2117395, 'name': 'Skyler Messinger', 'slug': 'messinger-skyler', 'userCount': 1, 'team': {'id': 453381, 'name': 'Spokane Indians', 'nameCode': 'SPO', 'slug': 'spokane-indians', 'national': False, 'sport': {'id': 64, 'slug': 'baseball', 'name': 'Baseball'}, 'userCount': 40, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'هنود سبوكين'}, 'shortNameTranslation': {}}}, 'deceased': False, 'country': {'alpha2': 'US', 'name': 'USA', 'slug': 'usa'}, 'shortName': 'S. Messinger', 'position': '3B', 'jerseyNumber': '3', 'fieldTranslations': {'nameTranslation': {'ar': 'س. ميسنجر'}, 'shortNameTranslation': {}}}, 'score': 266.76318, 'type': 'player'}, {'entity': {'id': 2222917, 'name': 'Cristian Messina', 'slug': 'cristian-messina', 'userCount': 1, 'team': {'id': 1115136, 'name': 'Virtus Vercelli', 'nameCode': 'VVE', 'slug': 'virtus-vercelli', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 6, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M'}, 'deceased': False, 'country': {'alpha2': 'IT', 'name': 'Italy', 'slug': 'italy'}, 'shortName': 'C. Messina', 'position': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'ك. ميسينا'}, 'shortNameTranslation': {}}}, 'score': 266.76318, 'type': 'player'}, {'entity': {'id': 1864508, 'name': 'Catherine Messina', 'slug': 'catherine-messina', 'userCount': 1, 'team': {'id': 467751, 'name': 'Cameroon Women', 'nameCode': 'CWO', 'slug': 'cameroon-women', 'national': False, 'sport': {'id': 62, 'slug': 'cricket', 'name': 'Cricket'}, 'userCount': 64, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'F', 'fieldTranslations': {'nameTranslation': {'ar': 'سي إم آر-دبليو'}, 'shortNameTranslation': {}}}, 'deceased': False, 'country': {'alpha2': 'CM', 'name': 'Cameroon', 'slug': 'cameroon'}, 'shortName': 'Catherine Messina', 'position': 'B', 'fieldTranslations': {'nameTranslation': {'ar': 'ك. ميسينا'}, 'shortNameTranslation': {}}}, 'score': 266.46536, 'type': 'player'}, {'entity': {'id': 2787, 'name': 'Jose Aleixo Ferreira Mamede', 'slug': 'jose-aleixo-ferreira-mamede', 'userCount': 1, 'team': {'id': 2720, 'name': 'Messina', 'nameCode': 'MES', 'slug': 'messina', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 3383, 'teamColors': {'primary': '#ff0000', 'secondary': '#000000', 'text': '#000000'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'سينا'}, 'shortNameTranslation': {}}}, 'deceased': False, 'shortName': 'J. A. F. Mamede', 'fieldTranslations': {'nameTranslation': {'ar': 'خ. ماميدي'}, 'shortNameTranslation': {}}}, 'score': 263.8449, 'type': 'player'}, {'entity': {'id': 2000145, 'name': 'Arthur Messias Martins', 'slug': 'arthur-messias-martins', 'userCount': 1, 'team': {'id': 933899, 'name': 'Paysandu U17', 'nameCode': 'PAY', 'slug': 'paysandu-u17', 'national': False, 'sport': {'id': 2, 'slug': 'basketball', 'name': 'Basketball'}, 'userCount': 12, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'بايساندو تحت 17'}, 'shortNameTranslation': {}}}, 'deceased': False, 'country': {'alpha2': 'BR', 'name': 'Brazil', 'slug': 'brazil'}, 'shortName': 'A. M. Martins', 'jerseyNumber': '1', 'fieldTranslations': {'nameTranslation': {'ar': 'آ. مارتينز'}, 'shortNameTranslation': {}}}, 'score': 263.8449, 'type': 'player'}, {'entity': {'id': 821496, 'name': 'Panayiotis Drougas', 'slug': 'panayiotis-drougas', 'userCount': 1, 'team': {'id': 8026, 'name': 'GS Messiniakos', 'nameCode': 'GME', 'slug': 'messiniakos-gs', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 42, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'ميسينيكوس'}, 'shortNameTranslation': {}}}, 'deceased': False, 'country': {'alpha2': 'GR', 'name': 'Greece', 'slug': 'greece'}, 'shortName': 'P. Drougas', 'position': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'ب. دروجاس'}, 'shortNameTranslation': {}}}, 'score': 262.269, 'type': 'player'}, {'entity': {'id': 1510472, 'name': 'Francesco Messina', 'slug': 'francesco-messina', 'userCount': 1, 'team': {'id': 447402, 'name': 'Città di Cossato', 'nameCode': 'CDC', 'slug': 'usd-citta-di-cossato', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 10, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'fieldTranslations': {'nameTranslation': {'ar': 'كوساتو'}, 'shortNameTranslation': {}}}, 'deceased': False, 'country': {'alpha2': 'IT', 'name': 'Italy', 'slug': 'italy'}, 'shortName': 'F. Messina', 'position': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'ف. ميسينا'}, 'shortNameTranslation': {}}}, 'score': 261.74155, 'type': 'player'}, {'entity': {'id': 1658047, 'name': 'Dalton Messina', 'slug': 'messina-dalton', 'userCount': 1, 'team': {'id': 249706, 'name': 'Ohio State Buckeyes', 'nameCode': 'OSU', 'slug': 'ohio-state-buckeyes', 'national': False, 'sport': {'id': 4, 'slug': 'ice-hockey', 'name': 'Ice hockey'}, 'userCount': 125, 'teamColors': {'primary': '#ce0f3d', 'secondary': '#b0b7bc', 'text': '#b0b7bc'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'أوهايو ستيت'}, 'shortNameTranslation': {}}}, 'deceased': False, 'country': {'alpha2': 'US', 'name': 'USA', 'slug': 'usa'}, 'shortName': 'D. Messina', 'position': 'F', 'fieldTranslations': {'nameTranslation': {'ar': 'د. ميسينا'}, 'shortNameTranslation': {}}}, 'score': 261.74155, 'type': 'player'}, {'entity': {'id': 2234924, 'name': 'Kaylan Messias da Silva Lima', 'slug': 'kaylan-messias-da-silva-lima', 'userCount': 1, 'team': {'id': 1112204, 'name': 'A7 SC U7', 'nameCode': 'ASU', 'slug': 'a7-sc-u7', 'national': False, 'sport': {'id': 29, 'slug': 'futsal', 'name': 'Futsal'}, 'userCount': 1, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}}, 'deceased': False, 'country': {'alpha2': 'BR', 'name': 'Brazil', 'slug': 'brazil'}, 'shortName': 'K. M. d. S. Lima', 'fieldTranslations': {'nameTranslation': {'ar': 'ك. ليما'}, 'shortNameTranslation': {}}}, 'score': 261.253, 'type': 'player'}, {'entity': {'id': 2139343, 'name': 'Messiah Delhomme', 'slug': 'delhomme-messiah', 'userCount': 1, 'team': {'id': 4306, 'name': 'Maryland Terrapins', 'nameCode': 'MD', 'slug': 'maryland-terrapins', 'national': False, 'sport': {'id': 63, 'slug': 'american-football', 'name': 'American football'}, 'userCount': 633, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'ماريلاند'}, 'shortNameTranslation': {}}}, 'deceased': False, 'shortName': 'M. Delhomme', 'position': 'DB', 'fieldTranslations': {'nameTranslation': {'ar': 'م. ديلوم'}, 'shortNameTranslation': {}}}, 'score': 258.64005, 'type': 'player'}, {'entity': {'id': 1820565, 'name': 'Salvatore Messina', 'slug': 'salvatore-messina', 'userCount': 1, 'team': {'id': 391545, 'name': 'Castellammare 94', 'nameCode': 'C94', 'slug': 'asd-castellammare-calcio-94', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 46, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'كاستيللاماري 94'}, 'shortNameTranslation': {}}}, 'deceased': False, 'country': {'alpha2': 'IT', 'name': 'Italy', 'slug': 'italy'}, 'shortName': 'S. Messina', 'position': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'س. ميسينا'}, 'shortNameTranslation': {}}}, 'score': 258.20273, 'type': 'player'}, {'entity': {'id': 1690990, 'name': 'Parker Messick', 'slug': 'messick-parker', 'userCount': 1, 'team': {'id': 3650, 'name': 'Cleveland Guardians', 'nameCode': 'CLE', 'slug': 'cleveland-guardians', 'national': False, 'sport': {'id': 64, 'slug': 'baseball', 'name': 'Baseball'}, 'userCount': 15129, 'teamColors': {'primary': '#e41937', 'secondary': '#e41937', 'text': '#e41937'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'غارديانز', 'hi': 'गार्डियंस', 'bn': 'গার্ডিয়ানস'}, 'shortNameTranslation': {}}}, 'deceased': False, 'country': {'alpha2': 'US', 'name': 'USA', 'slug': 'usa'}, 'shortName': 'P. Messick', 'position': 'P', 'jerseyNumber': '77', 'fieldTranslations': {'nameTranslation': {'ar': 'ب. ميسيك'}, 'shortNameTranslation': {}}}, 'score': 258.20273, 'type': 'player'}, {'entity': {'id': 1879722, 'name': 'Brandon Messina', 'slug': 'brandon-messina', 'userCount': 1, 'team': {'id': 386961, 'name': 'FC Amical Saint-Prex', 'nameCode': 'FAS', 'slug': 'fc-amical-saint-prex', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 138, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'أميكال سانت بريكس', 'hi': 'ऍफ़सी अमिकल साँ-प्रिक्स'}, 'shortNameTranslation': {}}}, 'deceased': False, 'country': {'alpha2': 'CH', 'name': 'Switzerland', 'slug': 'switzerland'}, 'shortName': 'B. Messina', 'position': 'M', 'jerseyNumber': '9', 'fieldTranslations': {'nameTranslation': {'ar': 'ب. ميسينا'}, 'shortNameTranslation': {}}}, 'score': 258.20273, 'type': 'player'}, {'entity': {'id': 1624037, 'name': 'Messiah Blair', 'slug': 'blair-messiah', 'userCount': 1, 'team': {'id': 4349, 'name': 'Eastern Michigan Eagles', 'nameCode': 'EMU', 'slug': 'eastern-michigan-eagles', 'national': False, 'sport': {'id': 63, 'slug': 'american-football', 'name': 'American football'}, 'userCount': 136, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'ميشيغان الشرقية'}, 'shortNameTranslation': {}}}, 'deceased': False, 'shortName': 'M. Blair', 'position': 'DE', 'jerseyNumber': '53', 'fieldTranslations': {'nameTranslation': {'ar': 'م. بلير'}, 'shortNameTranslation': {}}}, 'score': 255.26703, 'type': 'player'}, {'entity': {'id': 1872353, 'name': 'Ioannis Messios', 'slug': 'ioannis-messios', 'userCount': 1, 'team': {'id': 523243, 'name': 'A.S Lythrodontas 2023', 'nameCode': 'AL2', 'slug': 'as-lythrodontas-2023', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 12, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'ليثرودونتاس'}, 'shortNameTranslation': {}}}, 'deceased': False, 'country': {'alpha2': 'CY', 'name': 'Cyprus', 'slug': 'cyprus'}, 'shortName': 'I. Messios', 'position': 'F', 'jerseyNumber': '7', 'fieldTranslations': {'nameTranslation': {'ar': 'ي. ميسيوس'}, 'shortNameTranslation': {}}}, 'score': 254.5558, 'type': 'player'}, {'entity': {'id': 1608432, 'name': 'Domenico Messina', 'slug': 'domenico-messina', 'userCount': 1, 'team': {'id': 1120309, 'name': 'Atletico Partinico', 'nameCode': 'APA', 'slug': 'atletico-partinico', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 2, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M'}, 'deceased': False, 'country': {'alpha2': 'IT', 'name': 'Italy', 'slug': 'italy'}, 'shortName': 'D. Messina', 'position': 'F', 'fieldTranslations': {'nameTranslation': {'ar': 'د. ميسينا'}, 'shortNameTranslation': {}}}, 'score': 253.28125, 'type': 'player'}, {'entity': {'id': 1624849, 'name': 'Messiah deWeaver', 'slug': 'deweaver-messiah', 'userCount': 1, 'team': {'id': 85567, 'name': 'Old Dominion Monarchs', 'nameCode': 'ODU', 'slug': 'old-dominion-monarchs', 'national': False, 'sport': {'id': 63, 'slug': 'american-football', 'name': 'American football'}, 'userCount': 119, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'دومينيون القديمة'}, 'shortNameTranslation': {}}}, 'deceased': False, 'shortName': 'M. deWeaver', 'position': 'QB', 'jerseyNumber': '7', 'fieldTranslations': {'nameTranslation': {'ar': 'م. دي ويفر'}, 'shortNameTranslation': {}}}, 'score': 251.55815, 'type': 'player'}, {'entity': {'id': 2279762, 'name': 'Aiden Messinger', 'slug': 'aiden-messinger', 'userCount': 1, 'team': {'id': 329851, 'name': 'Bowling Green Falcons', 'nameCode': 'BGF', 'slug': 'bowling-green-falcons', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 21, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'باولينغ غرين فالكونز'}, 'shortNameTranslation': {}}}, 'deceased': False, 'country': {'alpha2': 'CA', 'name': 'Canada', 'slug': 'canada'}, 'shortName': 'A. Messinger', 'position': 'D', 'fieldTranslations': {'nameTranslation': {'ar': 'أ. ميسينجر'}, 'shortNameTranslation': {}}}, 'score': 250.73123, 'type': 'player'}, {'entity': {'id': 2332263, 'name': 'Alvaro Messiah', 'slug': 'alvaro-messiah', 'userCount': 1, 'team': {'id': 301540, 'name': 'Deportivo La Coruña U19', 'nameCode': 'DLC', 'slug': 'deportivo-la-coruna-u19', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 639, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'gender': 'M', 'fieldTranslations': {'nameTranslation': {'ar': 'ديبورتيفو لا كورونيا تحت 19'}, 'shortNameTranslation': {}}}, 'deceased': False, 'shortName': 'A. Messiah'}, 'score': 250.43715, 'type': 'player'}, {'entity': {'id': 1829480, 'name': 'Gustavo Messias Dos Santos', 'slug': 'gustavo-messias-dos-santos', 'userCount': 1, 'team': {'id': 463638, 'name': 'Correria FC', 'nameCode': 'CFC', 'slug': 'correria-fc', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 12, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'fieldTranslations': {'nameTranslation': {'ar': 'كوريريا'}, 'shortNameTranslation': {}}}, 'deceased': False, 'country': {'alpha2': 'BR', 'name': 'Brazil', 'slug': 'brazil'}, 'shortName': 'G. M. D. Santos', 'fieldTranslations': {'nameTranslation': {'ar': 'غ. دوس سانتوس'}, 'shortNameTranslation': {}}}, 'score': 249.47507, 'type': 'player'}]

In [5]:
df = pd.DataFrame(data)
df

                                               entity      score    type
0   {'id': 2117395, 'name': 'Skyler Messinger', 's...  266.76318  player
1   {'id': 2222917, 'name': 'Cristian Messina', 's...  266.76318  player
2   {'id': 1864508, 'name': 'Catherine Messina', '...  266.46536  player
3   {'id': 2787, 'name': 'Jose Aleixo Ferreira Mam...  263.84490  player
4   {'id': 2000145, 'name': 'Arthur Messias Martin...  263.84490  player
5   {'id': 821496, 'name': 'Panayiotis Drougas', '...  262.26900  player
6   {'id': 1510472, 'name': 'Francesco Messina', '...  261.74155  player
7   {'id': 1658047, 'name': 'Dalton Messina', 'slu...  261.74155  player
8   {'id': 2234924, 'name': 'Kaylan Messias da Sil...  261.25300  player
9   {'id': 2139343, 'name': 'Messiah Delhomme', 's...  258.64005  player
10  {'id': 1820565, 'name': 'Salvatore Messina', '...  258.20273  player
11  {'id': 1690990, 'name': 'Parker Messick', 'slu...  258.20273  player
12  {'id': 1879722, 'name': 'Brandon Messina', 'sl...  258.20273  player
13  {'id': 1624037, 'name': 'Messiah Blair', 'slug...  255.26703  player
14  {'id': 1872353, 'name': 'Ioannis Messios', 'sl...  254.55580  player
15  {'id': 1608432, 'name': 'Domenico Messina', 's...  253.28125  player
16  {'id': 1624849, 'name': 'Messiah deWeaver', 's...  251.55815  player
17  {'id': 2279762, 'name': 'Aiden Messinger', 'sl...  250.73123  player
18  {'id': 2332263, 'name': 'Alvaro Messiah', 'slu...  250.43715  player
19  {'id': 1829480, 'name': 'Gustavo Messias Dos S...  249.47507  player

In [6]:
df_flat = pd.json_normalize(df['entity'])
df_flat['score'] = df['score']
df_flat['type'] = df['type']
df_flat

,id,name,slug,userCount,deceased,shortName,position,jerseyNumber,team.id,team.name,...,team.gender,team.fieldTranslations.nameTranslation.ar,country.alpha2,country.name,country.slug,fieldTranslations.nameTranslation.ar,team.fieldTranslations.nameTranslation.hi,team.fieldTranslations.nameTranslation.bn,score,type
0,2117395,Skyler Messinger,messinger-skyler,1,False,S. Messinger,3B,3,453381,Spokane Indians,...,M,هنود سبوكين,US,USA,usa,س. ميسنجر,NaN,NaN,266.76318,player
1,2222917,Cristian Messina,cristian-messina,1,False,C. Messina,M,NaN,1115136,Virtus Vercelli,...,M,NaN,IT,Italy,italy,ك. ميسينا,NaN,NaN,266.76318,player
2,1864508,Catherine Messina,catherine-messina,1,False,Catherine Messina,B,NaN,467751,Cameroon Women,...,F,سي إم آر-دبليو,CM,Cameroon,cameroon,ك. ميسينا,NaN,NaN,266.46536,player
3,2787,Jose Aleixo Ferreira Mamede,jose-aleixo-ferreira-mamede,1,False,J. A. F. Mamede,NaN,NaN,2720,Messina,...,M,سينا,NaN,NaN,NaN,خ. ماميدي,NaN,NaN,263.84490,player
4,2000145,Arthur Messias Martins,arthur-messias-martins,1,False,A. M. Martins,NaN,1,933899,Paysandu U17,...,M,بايساندو تحت 17,BR,Brazil,brazil,آ. مارتينز,NaN,NaN,263.84490,player
5,821496,Panayiotis Drougas,panayiotis-drougas,1,False,P. Drougas,M,NaN,8026,GS Messiniakos,...,M,ميسينيكوس,GR,Greece,greece,ب. دروجاس,NaN,NaN,262.26900,player
6,1510472,Francesco Messina,francesco-messina,1,False,F. Messina,M,NaN,447402,Città di Cossato,...,NaN,كوساتو,IT,Italy,italy,ف. ميسينا,NaN,NaN,261.74155,player
7,1658047,Dalton Messina,messina-dalton,1,False,D. Messina,F,NaN,249706,Ohio State Buckeyes,...,M,أوهايو ستيت,US,USA,usa,د. ميسينا,NaN,NaN,261.74155,player
8,2234924,Kaylan Messias da Silva Lima,kaylan-messias-da-silva-lima,1,False,K. M. d. S. Lima,NaN,NaN,1112204,A7 SC U7,...,NaN,NaN,BR,Brazil,brazil,ك. ليما,NaN,NaN,261.25300,player
9,2139343,Messiah Delhomme,delhomme-messiah,1,False,M. Delhomme,DB,NaN,4306,Maryland Terrapins,...,M,ماريلاند,NaN,NaN,NaN,م. ديلوم,NaN,NaN,258.64005,player
10,1820565,Salvatore Messina,salvatore-messina,1,False,S. Messina,M,NaN,391545,Castellammare 94,...,M,كاستيللاماري 94,IT,Italy,italy,س. ميسينا,NaN,NaN,258.20273,player
11,1690990,Parker Messick,messick-parker,1,False,P. Messick,P,77,3650,Cleveland Guardians,...,M,غارديانز,US,USA,usa,ب. ميسيك,गार्डियंस,গার্ডিয়ানস,258.20273,player
12,1879722,Brandon Messina,brandon-messina,1,False,B. Messina,M,9,386961,FC Amical Saint-Prex,...,M,أميكال سانت بريكس,CH,Switzerland,switzerland,ب. ميسينا,ऍफ़सी अमिकल साँ-प्रिक्स,NaN,258.20273,player
13,1624037,Messiah Blair,blair-messiah,1,False,M. Blair,DE,53,4349,Eastern Michigan Eagles,...,M,ميشيغان الشرقية,NaN,NaN,NaN,م. بلير,NaN,NaN,255.26703,player
14,1872353,Ioannis Messios,ioannis-messios,1,False,I. Messios,F,7,523243,A.S Lythrodontas 2023,...,M,ليثرودونتاس,CY,Cyprus,cyprus,ي. ميسيوس,NaN,NaN,254.55580,player
15,1608432,Domenico Messina,domenico-messina,1,False,D. Messina,F,NaN,1120309,Atletico Partinico,...,M,NaN,IT,Italy,italy,د. ميسينا,NaN,NaN,253.28125,player
16,1624849,Messiah deWeaver,deweaver-messiah,1,False,M. deWeaver,QB,7,85567,Old Dominion Monarchs,...,M,دومينيون القديمة,NaN,NaN,NaN,م. دي ويفر,NaN,NaN,251.55815,player
17,2279762,Aiden Messinger,aiden-messinger,1,False,A. Messinger,D,NaN,329851,Bowling Green Falcons,...,M,باولينغ غرين فالكونز,CA,Canada,canada,أ. ميسينجر,NaN,NaN,250.73123,player
18,2332263,Alvaro Messiah,alvaro-messiah,1,False,A. Messiah,NaN,NaN,301540,Deportivo La Coruña U19,...,M,ديبورتيفو لا كورونيا تحت 19,NaN,NaN,NaN,NaN,NaN,NaN,250.43715,player
19,1829480,Gustavo Messias Dos Santos,gustavo-messias-dos-santos,1,False,G. M. D. Santos,NaN,NaN,463638,Correria FC,...,NaN,كوريريا,BR,Brazil,brazil,غ. دوس سانتوس,NaN,NaN,249.47507,player

# **Scrapping team data (Real Madrid)**

In [74]:
url = "http://footballapi.eastus.azurecontainer.io:3000/teams/search?q=Real%20madrid&page=0"

In [75]:
response = requests.get(url)
data = response.json()

In [76]:
print(data)

[{'entity': {'id': 2829, 'name': 'Real Madrid', 'nameCode': 'RMA', 'slug': 'real-madrid', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 6107280, 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'type': 0, 'gender': 'M', 'country': {'alpha2': 'ES', 'name': 'Spain', 'slug': 'spain'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'ru': 'Реал Мадрид', 'hi': 'रियल मैड्रिड', 'bn': 'রিয়াল মাদ্রিদ'}, 'shortNameTranslation': {}}}, 'score': 8914358, 'type': 'team'}, {'entity': {'id': 305051, 'name': 'Real Madrid', 'nameCode': 'RMC', 'slug': 'real-madrid', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 165291, 'teamColors': {'primary': '#ffffff', 'secondary': '#d90e4c', 'text': '#d90e4c'}, 'type': 0, 'gender': 'F', 'country': {'alpha2': 'ES', 'name': 'Spain', 'slug': 'spain'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'hi': 'रियल माद्रिद सीऍफ़'}, 'shortNameTranslation': {}}}, 'score': 1297249, 'type': 'team'}, {'entity': {'id': 5069, 'name': 'Real Madrid Castilla U21', 'nameCode': 'RMC', 'slug': 'real-madrid-castilla', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 43552, 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'type': 0, 'gender': 'M', 'country': {'alpha2': 'ES', 'name': 'Spain', 'slug': 'spain'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد كاستيا', 'ru': 'Реал Мадрид Б', 'hi': 'रियल माद्रिद कास्टिला'}, 'shortNameTranslation': {}}}, 'score': 710468.44, 'type': 'team'}, {'entity': {'id': 1082046, 'name': 'Real Madrid Leyendas', 'nameCode': 'RML', 'slug': 'real-madrid-legends', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 20309, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'type': 0, 'gender': 'M', 'country': {'alpha2': 'ES', 'name': 'Spain', 'slug': 'spain'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد ليجنداس'}, 'shortNameTranslation': {}}}, 'score': 531512.94, 'type': 'team'}, {'entity': {'id': 120854, 'name': 'Real Madrid U19', 'nameCode': 'RMA', 'slug': 'real-madrid-u19', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 20178, 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'type': 0, 'gender': 'M', 'country': {'alpha2': 'ES', 'name': 'Spain', 'slug': 'spain'}, 'fieldTranslations': {'nameTranslation': {'ar': 'Real Madrid تحت 19', 'ru': 'Реал Мадрид U19', 'hi': 'रियल माद्रिद U19'}, 'shortNameTranslation': {}}}, 'score': 464669.97, 'type': 'team'}, {'entity': {'id': 490780, 'name': 'Real Madrid C', 'nameCode': 'REA', 'slug': 'real-madrid-c', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 8124, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'type': 0, 'gender': 'M', 'country': {'alpha2': 'ES', 'name': 'Spain', 'slug': 'spain'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد سي'}, 'shortNameTranslation': {}}}, 'score': 344905.22, 'type': 'team'}, {'entity': {'id': 154810, 'name': 'Real Madrid U18', 'nameCode': 'RMA', 'slug': 'real-madrid-u18', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 4948, 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'type': 0, 'country': {'alpha2': 'ES', 'name': 'Spain', 'slug': 'spain'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد'}, 'shortNameTranslation': {}}}, 'score': 254728.33, 'type': 'team'}, {'entity': {'id': 497599, 'name': 'Real Madrid B', 'nameCode': 'RMB', 'slug': 'real-madrid-b', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 3622, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'type': 0, 'gender': 'F', 'country': {'alpha2': 'ES', 'name': 'Spain', 'slug': 'spain'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد ب'}, 'shortNameTranslation': {}}}, 'score': 230111.11, 'type': 'team'}, {'entity': {'id': 1089499, 'name': 'Real Madrid U17', 'nameCode': 'RMU', 'slug': 'real-madrid-u17', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 1070, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'type': 0, 'gender': 'M', 'country': {'alpha2': 'ES', 'name': 'Spain', 'slug': 'spain'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد تحت 17'}, 'shortNameTranslation': {}}}, 'score': 121670.2, 'type': 'team'}, {'entity': {'id': 1074055, 'name': 'Real Madrid FC', 'nameCode': 'RMF', 'slug': 'real-madrid-fc', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 783, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'type': 0, 'gender': 'F', 'country': {'alpha2': 'BR', 'name': 'Brazil', 'slug': 'brazil'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد'}, 'shortNameTranslation': {}}}, 'score': 102165.7, 'type': 'team'}, {'entity': {'id': 77393, 'name': 'RSC Internacional FC', 'nameCode': 'RSC', 'slug': 'rsc-internacional-fc', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 1946, 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'type': 0, 'gender': 'M', 'country': {'alpha2': 'ES', 'name': 'Spain', 'slug': 'spain'}, 'fieldTranslations': {'nameTranslation': {'ar': 'C ريال مدريد', 'ru': 'Реал Мадрид С'}, 'shortNameTranslation': {}}}, 'score': 93961.875, 'type': 'team'}, {'entity': {'id': 515338, 'name': 'Real Madrid Colinas', 'nameCode': 'RMC', 'slug': 'real-madrid-colinas', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 594, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'type': 0, 'gender': 'M', 'country': {'alpha2': 'BR', 'name': 'Brazil', 'slug': 'brazil'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد كولينا'}, 'shortNameTranslation': {}}}, 'score': 77685.81, 'type': 'team'}, {'entity': {'id': 930857, 'name': 'Real Madrid Potrero Bajada', 'nameCode': 'RMA', 'slug': 'real-madrid-de-bobadal', 'national': False, 'sport': {'id': 1, 'slug': 'football', 'name': 'Football'}, 'userCount': 406, 'teamColors': {'primary': '#374df5', 'secondary': '#374df5', 'text': '#ffffff'}, 'type': 0, 'gender': 'M', 'country': {'alpha2': 'AR', 'name': 'Argentina', 'slug': 'argentina'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد (PB)'}, 'shortNameTranslation': {}}}, 'score': 67814.69, 'type': 'team'}]

In [77]:
df2 = pd.DataFrame(data)
df2

                                               entity        score  type
0   {'id': 2829, 'name': 'Real Madrid', 'nameCode'...  8914358.000  team
1   {'id': 305051, 'name': 'Real Madrid', 'nameCod...  1297249.000  team
2   {'id': 5069, 'name': 'Real Madrid Castilla U21...   710468.440  team
3   {'id': 1082046, 'name': 'Real Madrid Leyendas'...   531512.940  team
4   {'id': 120854, 'name': 'Real Madrid U19', 'nam...   464669.970  team
5   {'id': 490780, 'name': 'Real Madrid C', 'nameC...   344905.220  team
6   {'id': 154810, 'name': 'Real Madrid U18', 'nam...   254728.330  team
7   {'id': 497599, 'name': 'Real Madrid B', 'nameC...   230111.110  team
8   {'id': 1089499, 'name': 'Real Madrid U17', 'na...   121670.200  team
9   {'id': 1074055, 'name': 'Real Madrid FC', 'nam...   102165.700  team
10  {'id': 77393, 'name': 'RSC Internacional FC', ...    93961.875  team
11  {'id': 515338, 'name': 'Real Madrid Colinas', ...    77685.810  team
12  {'id': 930857, 'name': 'Real Madrid Potrero Ba...    67814.690  team

In [78]:
df2_flat = pd.json_normalize(df2['entity'])
df2_flat['score'] = df2['score']
df2_flat['type'] = df2['type']
df2_flat

,id,name,nameCode,slug,national,userCount,type,gender,sport.id,sport.slug,...,teamColors.secondary,teamColors.text,country.alpha2,country.name,country.slug,fieldTranslations.nameTranslation.ar,fieldTranslations.nameTranslation.ru,fieldTranslations.nameTranslation.hi,fieldTranslations.nameTranslation.bn,score
0,2829,Real Madrid,RMA,real-madrid,False,6107280,team,M,1,football,...,#004996,#004996,ES,Spain,spain,ريال مدريد,Реал Мадрид,रियल मैड्रिड,রিয়াল মাদ্রিদ,8914358.000
1,305051,Real Madrid,RMC,real-madrid,False,165291,team,F,1,football,...,#d90e4c,#d90e4c,ES,Spain,spain,ريال مدريد,NaN,रियल माद्रिद सीऍफ़,NaN,1297249.000
2,5069,Real Madrid Castilla U21,RMC,real-madrid-castilla,False,43552,team,M,1,football,...,#004996,#004996,ES,Spain,spain,ريال مدريد كاستيا,Реал Мадрид Б,रियल माद्रिद कास्टिला,NaN,710468.440
3,1082046,Real Madrid Leyendas,RML,real-madrid-legends,False,20309,team,M,1,football,...,#374df5,#ffffff,ES,Spain,spain,ريال مدريد ليجنداس,NaN,NaN,NaN,531512.940
4,120854,Real Madrid U19,RMA,real-madrid-u19,False,20178,team,M,1,football,...,#004996,#004996,ES,Spain,spain,Real Madrid تحت 19,Реал Мадрид U19,रियल माद्रिद U19,NaN,464669.970
5,490780,Real Madrid C,REA,real-madrid-c,False,8124,team,M,1,football,...,#374df5,#ffffff,ES,Spain,spain,ريال مدريد سي,NaN,NaN,NaN,344905.220
6,154810,Real Madrid U18,RMA,real-madrid-u18,False,4948,team,NaN,1,football,...,#004996,#004996,ES,Spain,spain,ريال مدريد,NaN,NaN,NaN,254728.330
7,497599,Real Madrid B,RMB,real-madrid-b,False,3622,team,F,1,football,...,#374df5,#ffffff,ES,Spain,spain,ريال مدريد ب,NaN,NaN,NaN,230111.110
8,1089499,Real Madrid U17,RMU,real-madrid-u17,False,1070,team,M,1,football,...,#374df5,#ffffff,ES,Spain,spain,ريال مدريد تحت 17,NaN,NaN,NaN,121670.200
9,1074055,Real Madrid FC,RMF,real-madrid-fc,False,783,team,F,1,football,...,#374df5,#ffffff,BR,Brazil,brazil,ريال مدريد,NaN,NaN,NaN,102165.700
10,77393,RSC Internacional FC,RSC,rsc-internacional-fc,False,1946,team,M,1,football,...,#004996,#004996,ES,Spain,spain,C ريال مدريد,Реал Мадрид С,NaN,NaN,93961.875
11,515338,Real Madrid Colinas,RMC,real-madrid-colinas,False,594,team,M,1,football,...,#374df5,#ffffff,BR,Brazil,brazil,ريال مدريد كولينا,NaN,NaN,NaN,77685.810
12,930857,Real Madrid Potrero Bajada,RMA,real-madrid-de-bobadal,False,406,team,M,1,football,...,#374df5,#ffffff,AR,Argentina,argentina,ريال مدريد (PB),NaN,NaN,NaN,67814.690

# **Scrapping TeamID/Players**

In [98]:
url = "http://footballapi.eastus.azurecontainer.io:3000/teams/2829/players"

In [99]:
response = requests.get(url)
data2 = response.json()

In [100]:
print(data2)

{'players': [{'player': {'name': 'Kylian Mbappé', 'slug': 'kylian-mbappe', 'shortName': 'K. Mbappé', 'team': {'name': 'Real Madrid', 'slug': 'real-madrid', 'shortName': 'Real Madrid', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'tournament': {'name': 'LaLiga', 'slug': 'laliga', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'uniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'id': 8, 'country': {}, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'priority': 691, 'isLive': False, 'id': 36, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लीगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'primaryUniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'id': 8, 'country': {}, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'userCount': 6117089, 'nameCode': 'RMA', 'disabled': False, 'national': False, 'type': 0, 'id': 2829, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'ru': 'Реал Мадрид', 'hi': 'रियल मैड्रिड', 'bn': 'রিয়াল মাদ্রিদ'}, 'shortNameTranslation': {}}}, 'position': 'F', 'positionsDetailed': ['ST'], 'jerseyNumber': '10', 'height': 178, 'dateOfBirth': '1998-12-20T00:00:00+00:00', 'preferredFoot': 'Right', 'userCount': 1397390, 'deceased': False, 'gender': 'M', 'sofascoreId': 'KMbappé', 'id': 826643, 'country': {'alpha2': 'FR', 'alpha3': 'FRA', 'name': 'France', 'slug': 'france'}, 'shirtNumber': 10, 'dateOfBirthTimestamp': 914112000, 'contractUntilTimestamp': 1877472000, 'proposedMarketValue': 191000000, 'proposedMarketValueRaw': {'value': 191000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'كيليان مبابي', 'hi': 'किलियन एमबाप्पे', 'bn': 'কিলিয়ান এমবাপ্পে'}, 'shortNameTranslation': {'ar': 'ك. مبابي', 'hi': 'के. एमबाप्पे', 'bn': 'কে. এমবাপ্পে'}}}}, {'player': {'name': 'Vinícius Júnior', 'slug': 'vinicius-junior', 'shortName': 'Vinícius Jr.', 'team': {'name': 'Real Madrid', 'slug': 'real-madrid', 'shortName': 'Real Madrid', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'tournament': {'name': 'LaLiga', 'slug': 'laliga', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'uniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'id': 8, 'country': {}, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'priority': 691, 'isLive': False, 'id': 36, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लीगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'primaryUniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'id': 8, 'country': {}, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'userCount': 6117089, 'nameCode': 'RMA', 'disabled': False, 'national': False, 'type': 0, 'id': 2829, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'ru': 'Реал Мадрид', 'hi': 'रियल मैड्रिड', 'bn': 'রিয়াল মাদ্রিদ'}, 'shortNameTranslation': {}}}, 'position': 'F', 'positionsDetailed': ['ST', 'LW'], 'jerseyNumber': '7', 'height': 176, 'dateOfBirth': '2000-07-12T00:00:00+00:00', 'preferredFoot': 'Right', 'userCount': 1035572, 'deceased': False, 'gender': 'M', 'sofascoreId': 'ViniJr', 'id': 868812, 'country': {'alpha2': 'BR', 'alpha3': 'BRA', 'name': 'Brazil', 'slug': 'brazil'}, 'shirtNumber': 7, 'dateOfBirthTimestamp': 963360000, 'contractUntilTimestamp': 1814313600, 'proposedMarketValue': 156000000, 'proposedMarketValueRaw': {'value': 156000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'فينيسيوس جونيور', 'hi': 'विनीसियस जूनियर', 'bn': 'ভিনিসিয়াস জুনিয়র'}, 'shortNameTranslation': {'ar': 'فينيسيوس', 'hi': 'विनीसियस', 'bn': 'ভিনিসিয়াস'}}}}, {'player': {'name': 'Rodrygo', 'slug': 'rodrygo', 'shortName': 'Rodrygo', 'team': {'name': 'Real Madrid', 'slug': 'real-madrid', 'shortName': 'Real Madrid', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'tournament': {'name': 'LaLiga', 'slug': 'laliga', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'uniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'id': 8, 'country': {}, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'priority': 691, 'isLive': False, 'id': 36, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लीगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'primaryUniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'id': 8, 'country': {}, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'userCount': 6117089, 'nameCode': 'RMA', 'disabled': False, 'national': False, 'type': 0, 'id': 2829, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'ru': 'Реал Мадрид', 'hi': 'रियल मैड्रिड', 'bn': 'রিয়াল মাদ্রিদ'}, 'shortNameTranslation': {}}}, 'position': 'F', 'positionsDetailed': ['ST', 'RW'], 'jerseyNumber': '11', 'height': 174, 'dateOfBirth': '2001-01-09T00:00:00+00:00', 'preferredFoot': 'Right', 'userCount': 635613, 'deceased': False, 'gender': 'M', 'sofascoreId': 'Rodrygo', 'id': 910536, 'country': {'alpha2': 'BR', 'alpha3': 'BRA', 'name': 'Brazil', 'slug': 'brazil'}, 'shirtNumber': 11, 'dateOfBirthTimestamp': 978998400, 'contractUntilTimestamp': 1845936000, 'proposedMarketValue': 85000000, 'proposedMarketValueRaw': {'value': 85000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'رودريغو', 'hi': 'रोड्रिगो', 'bn': 'রড্রিগো'}, 'shortNameTranslation': {'ar': 'رودريغو', 'hi': 'रोड्रिगो', 'bn': 'রড্রিগো'}}}}, {'player': {'name': 'Endrick', 'slug': 'endrick', 'shortName': 'Endrick', 'team': {'name': 'Real Madrid', 'slug': 'real-madrid', 'shortName': 'Real Madrid', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'tournament': {'name': 'LaLiga', 'slug': 'laliga', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'uniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'id': 8, 'country': {}, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'priority': 691, 'isLive': False, 'id': 36, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लीगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'primaryUniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'id': 8, 'country': {}, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'userCount': 6117089, 'nameCode': 'RMA', 'disabled': False, 'national': False, 'type': 0, 'id': 2829, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'ru': 'Реал Мадрид', 'hi': 'रियल मैड्रिड', 'bn': 'রিয়াল মাদ্রিদ'}, 'shortNameTranslation': {}}}, 'position': 'F', 'positionsDetailed': ['ST'], 'jerseyNumber': '9', 'height': 173, 'dateOfBirth': '2006-07-21T00:00:00+00:00', 'preferredFoot': 'Left', 'userCount': 316748, 'deceased': False, 'gender': 'M', 'sofascoreId': 'Endrick', 'id': 1174937, 'country': {'alpha2': 'BR', 'alpha3': 'BRA', 'name': 'Brazil', 'slug': 'brazil'}, 'shirtNumber': 9, 'dateOfBirthTimestamp': 1153440000, 'contractUntilTimestamp': 1909008000, 'proposedMarketValue': 37000000, 'proposedMarketValueRaw': {'value': 37000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'إندريك فيليبي'}, 'shortNameTranslation': {'ar': 'إ. فيليبي'}}}}, {'player': {'name': 'Gonzalo García', 'firstName': 'Gonzalo García', 'slug': 'gonzalo-garcia', 'shortName': 'G. García', 'team': {'name': 'Real Madrid', 'slug': 'real-madrid', 'shortName': 'Real Madrid', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'tournament': {'name': 'LaLiga', 'slug': 'laliga', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'uniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'id': 8, 'country': {}, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'priority': 691, 'isLive': False, 'id': 36, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लीगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'primaryUniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'id': 8, 'country': {}, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'userCount': 6117089, 'nameCode': 'RMA', 'disabled': False, 'national': False, 'type': 0, 'id': 2829, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'ru': 'Реал Мадрид', 'hi': 'रियल मैड्रिड', 'bn': 'রিয়াল মাদ্রিদ'}, 'shortNameTranslation': {}}}, 'position': 'F', 'positionsDetailed': ['ST', 'LW'], 'jerseyNumber': '16', 'height': 182, 'dateOfBirth': '2004-03-24T00:00:00+00:00', 'preferredFoot': 'Right', 'userCount': 76308, 'deceased': False, 'gender': 'M', 'id': 1402716, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'shirtNumber': 16, 'dateOfBirthTimestamp': 1080086400, 'contractUntilTimestamp': 1909008000, 'proposedMarketValue': 15500000, 'proposedMarketValueRaw': {'value': 15500000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'غونزالو غارسيا', 'hi': 'गोंजालो गार्सिया', 'bn': 'গঞ্জালো গার্সিয়া'}, 'shortNameTranslation': {'ar': 'غ. غارسيا', 'hi': 'जी. गार्सिया', 'bn': 'জি. গার্সিয়া'}}}}, {'player': {'name': 'Jude Bellingham', 'slug': 'jude-bellingham', 'shortName': 'J. Bellingham', 'team': {'name': 'Real Madrid', 'slug': 'real-madrid', 'shortName': 'Real Madrid', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'tournament': {'name': 'LaLiga', 'slug': 'laliga', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'uniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'id': 8, 'country': {}, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'priority': 691, 'isLive': False, 'id': 36, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लीगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'primaryUniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'id': 8, 'country': {}, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'userCount': 6117089, 'nameCode': 'RMA', 'disabled': False, 'national': False, 'type': 0, 'id': 2829, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'ru': 'Реал Мадрид', 'hi': 'रियल मैड्रिड', 'bn': 'রিয়াল মাদ্রিদ'}, 'shortNameTranslation': {}}}, 'position': 'M', 'positionsDetailed': ['AM', 'MC'], 'jerseyNumber': '5', 'height': 188, 'dateOfBirth': '2003-06-29T00:00:00+00:00', 'preferredFoot': 'Right', 'userCount': 905702, 'deceased': False, 'gender': 'M', 'sofascoreId': 'JudeBell', 'id': 991011, 'country': {'alpha2': 'EN', 'alpha3': 'ENG', 'name': 'England', 'slug': 'england'}, 'shirtNumber': 5, 'dateOfBirthTimestamp': 1056844800, 'contractUntilTimestamp': 1877472000, 'proposedMarketValue': 170000000, 'proposedMarketValueRaw': {'value': 170000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'جود بيلينغهام', 'hi': 'जूड बेलिंघम', 'bn': 'জুড বেলিংহাম'}, 'shortNameTranslation': {'ar': 'ج. بيلينغهام', 'hi': 'जे. बेलिंघम', 'bn': 'জে. বেলিংহাম

In [101]:
print(type(data2))

<class 'dict'>

In [102]:
print(data2.keys())

dict_keys(['players', 'foreignPlayers', 'nationalPlayers', 'supportStaff', 'playerPreviousTeam', 'nationalTeamPlayerStatistics'])

In [103]:
df_players = pd.json_normalize(data2['players'])
print("Players Data:")
print(df_players.head())

Players Data:
       player.name      player.slug player.shortName player.team.name  \
0    Kylian Mbappé    kylian-mbappe        K. Mbappé      Real Madrid
1  Vinícius Júnior  vinicius-junior     Vinícius Jr.      Real Madrid
2          Rodrygo          rodrygo          Rodrygo      Real Madrid
3          Endrick          endrick          Endrick      Real Madrid
4   Gonzalo García   gonzalo-garcia        G. García      Real Madrid

  player.team.slug player.team.shortName player.team.gender  \
0      real-madrid           Real Madrid                  M
1      real-madrid           Real Madrid                  M
2      real-madrid           Real Madrid                  M
3      real-madrid           Real Madrid                  M
4      real-madrid           Real Madrid                  M

  player.team.sport.name player.team.sport.slug  player.team.sport.id  ...  \
0               Football               football                     1  ...
1               Football               football                     1  ...
2               Football               football                     1  ...
3               Football               football                     1  ...
4               Football               football                     1  ...

  player.fieldTranslations.shortNameTranslation.hi  \
0                                     के. एमबाप्पे
1                                         विनीसियस
2                                         रोड्रिगो
3                                              NaN
4                                     जी. गार्सिया

  player.fieldTranslations.shortNameTranslation.bn player.firstName  \
0                                     কে. এমবাপ্পে              NaN
1                                       ভিনিসিয়াস              NaN
2                                          রড্রিগো              NaN
3                                              NaN              NaN
4                                    জি. গার্সিয়া   Gonzalo García

  player.injury.reason player.injury.status player.injury.id  \
0                  NaN                  NaN              NaN
1                  NaN                  NaN              NaN
2                  NaN                  NaN              NaN
3                  NaN                  NaN              NaN
4                  NaN                  NaN              NaN

   player.injury.startDateTimestamp  player.injury.updateDateTimestamp  \
0                               NaN                                NaN
1                               NaN                                NaN
2                               NaN                                NaN
3                               NaN                                NaN
4                               NaN                                NaN

  player.injury.endDateTimestamp player.retired
0                            NaN            NaN
1                            NaN            NaN
2                            NaN            NaN
3                            NaN            NaN
4                            NaN            NaN

[5 rows x 135 columns]

In [104]:
df3 = pd.DataFrame(df_players)
df3

,player.name,player.slug,player.shortName,player.team.name,player.team.slug,player.team.shortName,player.team.gender,player.team.sport.name,player.team.sport.slug,player.team.sport.id,...,player.fieldTranslations.shortNameTranslation.hi,player.fieldTranslations.shortNameTranslation.bn,player.firstName,player.injury.reason,player.injury.status,player.injury.id,player.injury.startDateTimestamp,player.injury.updateDateTimestamp,player.injury.endDateTimestamp,player.retired
0,Kylian Mbappé,kylian-mbappe,K. Mbappé,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,के. एमबाप्पे,কে. এমবাপ্পে,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Vinícius Júnior,vinicius-junior,Vinícius Jr.,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,विनीसियस,ভিনিসিয়াস,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Rodrygo,rodrygo,Rodrygo,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,रोड्रिगो,রড্রিগো,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Endrick,endrick,Endrick,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Gonzalo García,gonzalo-garcia,G. García,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,जी. गार्सिया,জি. গার্সিয়া,Gonzalo García,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Jude Bellingham,jude-bellingham,J. Bellingham,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,जे. बेलिंघम,জে. বেলিংহাম,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Arda Güler,arda-guler,A. Güler,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ए. गुलेर,এ.গুলার,Arda Guler,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Federico Valverde,federico-valverde,F. Valverde,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,एफ. वेलवेर्डे,এফ. ভালভার্দে,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Brahim Díaz,brahim-diaz,B. Díaz,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,बी. डियाज़,বি. দিয়াজ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Eduardo Camavinga,camavinga-eduardo,E. Camavinga,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ई. एडुआर्डो,ই. কামাভিঙ্গা,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Franco Mastantuono,franco-mastantuono,F. Mastantuono,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,एफ. मस्तांतुओनो,এফ. মাস্তানতুওনো,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Aurélien Tchouaméni,aurelien-tchouameni,A. Tchouaméni,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ए. टचौमेनी,এ. চৌমেনি,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Dani Ceballos,dani-ceballos,D. Ceballos,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,डी. सेबालोस,ডি. সেবেলোস,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Mario Martín,martin-mario,M. Martín,Getafe,getafe,Getafe,M,Football,football,1,...,एम. मार्टिन,এম. মার্টিন,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Antonio Rüdiger,antonio-rudiger,A. Rüdiger,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ए. रुडिगर,এ. রুডিগার,NaN,Thigh Injury,out,4611.0,1.757635e+09,1.762085e+09,1.765152e+09,NaN
15,Trent Alexander-Arnold,trent-alexander-arnold,T. Alexander-Arnold,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,टी. अलेक्जेंडर-अर्नोल्ड,টি. আলেকজান্ডার-আর্নল্ড,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Daniel Carvajal,daniel-carvajal,D. Carvajal,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,डी. कार्वाजल,ডি. কারভাজাল,NaN,Knee Injury,dayToDay,9817.0,1.761523e+09,1.762085e+09,1.767917e+09,NaN
17,Dean Huijsen,dean-huijsen,D. Huijsen,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,डी. हुइजसेन,ডি. হুইজসেন,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Éder Militão,eder-militao,É. Militão,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ई. मिलिटाओ,এ. মিলিটাও,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Raúl Asencio,raul-asencio,R. Asencio,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,आर. असेंशियो,আর. অ্যাসেনসিও,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,David Alaba,david-alaba,D. Alaba,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,डी. अलाबा,ডি. আলাবা,NaN,Calf Injury,out,9247.0,1.760918e+09,1.762085e+09,1.762301e+09,NaN
21,Ferland Mendy,ferland-mendy,F. Mendy,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,एफ. मेंडी,এফ. মেন্ডি,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Fran García,fran-garcia,F. Garcia,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,एफ. गार्सिया,এফ. গার্সিয়া,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Álvaro Carreras,alvaro-carreras,Á. Carreras,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ए. कैरेरास,আ. ক্যারেরাস,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Thibaut Courtois,thibaut-courtois,T. Courtois,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,टी. कोर्टोइस,টি. কোর্টোইস,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Andriy Lunin,andriy-lunin,A. Lunin,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ए. लुनिन,এ. লুনিন,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [105]:
df_foreign = pd.json_normalize(data2['foreignPlayers'])
print("\nForeign Players:")
print(df_foreign.head())

Foreign Players:
          player.name         player.slug player.shortName player.team.name  \
0  Franco Mastantuono  franco-mastantuono   F. Mastantuono      Real Madrid
1         David Alaba         david-alaba         D. Alaba      Real Madrid
2    Thibaut Courtois    thibaut-courtois      T. Courtois      Real Madrid
3        Éder Militão        eder-militao       É. Militão      Real Madrid
4             Endrick             endrick          Endrick      Real Madrid

  player.team.slug player.team.shortName player.team.gender  \
0      real-madrid           Real Madrid                  M
1      real-madrid           Real Madrid                  M
2      real-madrid           Real Madrid                  M
3      real-madrid           Real Madrid                  M
4      real-madrid           Real Madrid                  M

  player.team.sport.name player.team.sport.slug  player.team.sport.id  ...  \
0               Football               football                     1  ...
1               Football               football                     1  ...
2               Football               football                     1  ...
3               Football               football                     1  ...
4               Football               football                     1  ...

  player.fieldTranslations.shortNameTranslation.hi  \
0                                  एफ. मस्तांतुओनो
1                                        डी. अलाबा
2                                     टी. कोर्टोइस
3                                       ई. मिलिटाओ
4                                              NaN

  player.fieldTranslations.shortNameTranslation.bn player.injury.reason  \
0                                 এফ. মাস্তানতুওনো                  NaN
1                                        ডি. আলাবা          Calf Injury
2                                     টি. কোর্টোইস                  NaN
3                                       এ. মিলিটাও                  NaN
4                                              NaN                  NaN

  player.injury.status player.injury.id player.injury.startDateTimestamp  \
0                  NaN              NaN                              NaN
1                  out           9247.0                     1.760918e+09
2                  NaN              NaN                              NaN
3                  NaN              NaN                              NaN
4                  NaN              NaN                              NaN

   player.injury.updateDateTimestamp  player.injury.endDateTimestamp  \
0                                NaN                             NaN
1                       1.762085e+09                    1.762301e+09
2                                NaN                             NaN
3                                NaN                             NaN
4                                NaN                             NaN

  player.firstName player.retired
0              NaN            NaN
1              NaN            NaN
2              NaN            NaN
3              NaN            NaN
4              NaN            NaN

[5 rows x 135 columns]

In [106]:
df4 = pd.DataFrame(df_foreign)
df4

,player.name,player.slug,player.shortName,player.team.name,player.team.slug,player.team.shortName,player.team.gender,player.team.sport.name,player.team.sport.slug,player.team.sport.id,...,player.fieldTranslations.shortNameTranslation.hi,player.fieldTranslations.shortNameTranslation.bn,player.injury.reason,player.injury.status,player.injury.id,player.injury.startDateTimestamp,player.injury.updateDateTimestamp,player.injury.endDateTimestamp,player.firstName,player.retired
0,Franco Mastantuono,franco-mastantuono,F. Mastantuono,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,एफ. मस्तांतुओनो,এফ. মাস্তানতুওনো,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,David Alaba,david-alaba,D. Alaba,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,डी. अलाबा,ডি. আলাবা,Calf Injury,out,9247.0,1.760918e+09,1.762085e+09,1.762301e+09,NaN,NaN
2,Thibaut Courtois,thibaut-courtois,T. Courtois,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,टी. कोर्टोइस,টি. কোর্টোইস,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Éder Militão,eder-militao,É. Militão,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ई. मिलिटाओ,এ. মিলিটাও,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Endrick,endrick,Endrick,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Rodrygo,rodrygo,Rodrygo,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,रोड्रिगो,রড্রিগো,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Vinícius Júnior,vinicius-junior,Vinícius Jr.,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,विनीसियस,ভিনিসিয়াস,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Antonio Rüdiger,antonio-rudiger,A. Rüdiger,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ए. रुडिगर,এ. রুডিগার,Thigh Injury,out,4611.0,1.757635e+09,1.762085e+09,1.765152e+09,NaN,NaN
8,Jude Bellingham,jude-bellingham,J. Bellingham,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,जे. बेलिंघम,জে. বেলিংহাম,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Trent Alexander-Arnold,trent-alexander-arnold,T. Alexander-Arnold,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,टी. अलेक्जेंडर-अर्नोल्ड,টি. আলেকজান্ডার-আর্নল্ড,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Aurélien Tchouaméni,aurelien-tchouameni,A. Tchouaméni,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ए. टचौमेनी,এ. চৌমেনি,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Eduardo Camavinga,camavinga-eduardo,E. Camavinga,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ई. एडुआर्डो,ই. কামাভিঙ্গা,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Ferland Mendy,ferland-mendy,F. Mendy,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,एफ. मेंडी,এফ. মেন্ডি,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Kylian Mbappé,kylian-mbappe,K. Mbappé,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,के. एमबाप्पे,কে. এমবাপ্পে,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Brahim Díaz,brahim-diaz,B. Díaz,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,बी. डियाज़,বি. দিয়াজ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Arda Güler,arda-guler,A. Güler,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ए. गुलेर,এ.গুলার,NaN,NaN,NaN,NaN,NaN,NaN,Arda Guler,NaN
16,Andriy Lunin,andriy-lunin,A. Lunin,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,ए. लुनिन,এ. লুনিন,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
17,Federico Valverde,federico-valverde,F. Valverde,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,एफ. वेलवेर्डे,এফ. ভালভার্দে,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
df_national = pd.json_normalize(data2['nationalPlayers'])
print("\nNational Players:")
print(df_national.head())

National Players:
         player.name        player.slug player.shortName player.team.name  \
0        David Alaba        david-alaba         D. Alaba      Real Madrid
1   Thibaut Courtois   thibaut-courtois      T. Courtois      Real Madrid
2       Éder Militão       eder-militao       É. Militão      Real Madrid
3      Kylian Mbappé      kylian-mbappe        K. Mbappé      Real Madrid
4  Federico Valverde  federico-valverde      F. Valverde      Real Madrid

  player.team.slug player.team.shortName player.team.gender  \
0      real-madrid           Real Madrid                  M
1      real-madrid           Real Madrid                  M
2      real-madrid           Real Madrid                  M
3      real-madrid           Real Madrid                  M
4      real-madrid           Real Madrid                  M

  player.team.sport.name player.team.sport.slug  player.team.sport.id  ...  \
0               Football               football                     1  ...
1               Football               football                     1  ...
2               Football               football                     1  ...
3               Football               football                     1  ...
4               Football               football                     1  ...

  player.proposedMarketValueRaw.value player.proposedMarketValueRaw.currency  \
0                             3600000                                    EUR
1                            19400000                                    EUR
2                            31000000                                    EUR
3                           191000000                                    EUR
4                           126000000                                    EUR

  player.fieldTranslations.nameTranslation.ar  \
0                                 ديفيد ألابا
1                                 تيبو كورتوا
2                               إيدير ميليتاو
3                                كيليان مبابي
4                           فيديريكو فالفيردي

  player.fieldTranslations.nameTranslation.hi  \
0                                 डेविड अलाबा
1                             थिबाउट कोर्टोइस
2                                 एडर मिलिटाओ
3                             किलियन एमबाप्पे
4                          फेडेरिको वेलवेर्डे

  player.fieldTranslations.nameTranslation.bn  \
0                                 ডেভিড আলাবা
1                             থিবাউট কোর্টোইস
2                                এডার মিলিটাও
3                            কিলিয়ান এমবাপ্পে
4                          ফেদেরিকো ভালভার্দে

  player.fieldTranslations.shortNameTranslation.ar  \
0                                         د. ألابا
1                                        ت. كورتوا
2                                       إ. ميليتاو
3                                         ك. مبابي
4                                      ف. فالفيردي

   player.fieldTranslations.shortNameTranslation.hi  \
0                                         डी. अलाबा
1                                      टी. कोर्टोइस
2                                        ई. मिलिटाओ
3                                      के. एमबाप्पे
4                                     एफ. वेलवेर्डे

   player.fieldTranslations.shortNameTranslation.bn player.retired  \
0                                         ডি. আলাবা            NaN
1                                      টি. কোর্টোইস            NaN
2                                        এ. মিলিটাও            NaN
3                                      কে. এমবাপ্পে            NaN
4                                     এফ. ভালভার্দে            NaN

  player.firstName
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN

[5 rows x 135 columns]

In [108]:
df5 = pd.DataFrame(df_national)
df5

,player.name,player.slug,player.shortName,player.team.name,player.team.slug,player.team.shortName,player.team.gender,player.team.sport.name,player.team.sport.slug,player.team.sport.id,...,player.proposedMarketValueRaw.value,player.proposedMarketValueRaw.currency,player.fieldTranslations.nameTranslation.ar,player.fieldTranslations.nameTranslation.hi,player.fieldTranslations.nameTranslation.bn,player.fieldTranslations.shortNameTranslation.ar,player.fieldTranslations.shortNameTranslation.hi,player.fieldTranslations.shortNameTranslation.bn,player.retired,player.firstName
0,David Alaba,david-alaba,D. Alaba,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,3600000,EUR,ديفيد ألابا,डेविड अलाबा,ডেভিড আলাবা,د. ألابا,डी. अलाबा,ডি. আলাবা,NaN,NaN
1,Thibaut Courtois,thibaut-courtois,T. Courtois,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,19400000,EUR,تيبو كورتوا,थिबाउट कोर्टोइस,থিবাউট কোর্টোইস,ت. كورتوا,टी. कोर्टोइस,টি. কোর্টোইস,NaN,NaN
2,Éder Militão,eder-militao,É. Militão,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,31000000,EUR,إيدير ميليتاو,एडर मिलिटाओ,এডার মিলিটাও,إ. ميليتاو,ई. मिलिटाओ,এ. মিলিটাও,NaN,NaN
3,Kylian Mbappé,kylian-mbappe,K. Mbappé,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,191000000,EUR,كيليان مبابي,किलियन एमबाप्पे,কিলিয়ান এমবাপ্পে,ك. مبابي,के. एमबाप्पे,কে. এমবাপ্পে,NaN,NaN
4,Federico Valverde,federico-valverde,F. Valverde,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,126000000,EUR,فيديريكو فالفيردي,फेडेरिको वेलवेर्डे,ফেদেরিকো ভালভার্দে,ف. فالفيردي,एफ. वेलवेर्डे,এফ. ভালভার্দে,NaN,NaN
5,Brahim Díaz,brahim-diaz,B. Díaz,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,42000000,EUR,إبراهيم دياز,ब्राहिम डियाज़,ব্রাহিম দিয়াজ,إ. دياز,बी. डियाज़,বি. দিয়াজ,NaN,NaN
6,Andriy Lunin,andriy-lunin,A. Lunin,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,16900000,EUR,أندري لونين,एंड्री लुनिन,অ্যান্ড্রি লুনিন,أ. لونين,ए. लुनिन,এ. লুনিন,False,NaN
7,Vinícius Júnior,vinicius-junior,Vinícius Jr.,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,156000000,EUR,فينيسيوس جونيور,विनीसियस जूनियर,ভিনিসিয়াস জুনিয়র,فينيسيوس,विनीसियस,ভিনিসিয়াস,NaN,NaN
8,Rodrygo,rodrygo,Rodrygo,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,85000000,EUR,رودريغو,रोड्रिगो,রড্রিগো,رودريغو,रोड्रिगो,রড্রিগো,NaN,NaN
9,Eduardo Camavinga,camavinga-eduardo,E. Camavinga,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,48000000,EUR,كامافينغا، إدواردو,"कैमाविंगा, एडुआर्डो","কামাভিঙ্গা, এডুয়ার্ডো",إ. كامافينغا,ई. एडुआर्डो,ই. কামাভিঙ্গা,NaN,NaN
10,Arda Güler,arda-guler,A. Güler,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,58000000,EUR,أردا غولر,अर्डा गुलेर,আরদা গুলার,أ. غولر,ए. गुलेर,এ.গুলার,NaN,Arda Guler
11,Dean Huijsen,dean-huijsen,D. Huijsen,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,77000000,EUR,دين هويسين,डीन हुइजसेन,ডিন হুইজসেন,د. هويسين,डी. हुइजसेन,ডি. হুইজসেন,NaN,NaN
12,Franco Mastantuono,franco-mastantuono,F. Mastantuono,Real Madrid,real-madrid,Real Madrid,M,Football,football,1,...,49000000,EUR,فرانكو ماستانتونو,फ्रेंको मस्तांतुओनो,ফ্রাঙ্কো মাস্তানতুওনো,ف. ماستانتونو,एफ. मस्तांतुओनो,এফ. মাস্তানতুওনো,NaN,NaN

In [109]:
df_support = pd.json_normalize(data2['supportStaff'])
print("\nSupport Staff:")
print(df_support.head())

Support Staff:
Empty DataFrame
Columns: []
Index: []

In [110]:

df_previous = pd.json_normalize(data2['playerPreviousTeam'])
print("\nplayer Previous Team:")
print(df_previous.head())

player Previous Team:
                transferDate         player.name         player.slug  \
0  2026-06-30T00:00:00+00:00        Mario Martín        martin-mario
1  2025-08-14T00:00:00+00:00  Franco Mastantuono  franco-mastantuono
2  2025-07-14T00:00:00+00:00     Álvaro Carreras     alvaro-carreras
3  2025-07-01T00:00:00+00:00      Gonzalo García      gonzalo-garcia
4  2025-06-01T00:00:00+00:00        Dean Huijsen        dean-huijsen

  player.shortName player.team.name player.team.slug player.team.shortName  \
0        M. Martín           Getafe           getafe                Getafe
1   F. Mastantuono      Real Madrid      real-madrid           Real Madrid
2      Á. Carreras      Real Madrid      real-madrid           Real Madrid
3        G. García      Real Madrid      real-madrid           Real Madrid
4       D. Huijsen      Real Madrid      real-madrid           Real Madrid

  player.team.gender player.team.sport.name player.team.sport.slug  ...  \
0                  M               Football               football  ...
1                  M               Football               football  ...
2                  M               Football               football  ...
3                  M               Football               football  ...
4                  M               Football               football  ...

   previousTeam.fieldTranslations.shortNameTranslation.hi player.firstName  \
0                                                NaN                   NaN
1                                               रिवर                   NaN
2                                                NaN                   NaN
3                                                NaN        Gonzalo García
4                                                NaN                   NaN

  previousTeam.fieldTranslations.shortNameTranslation.bn player.injury.reason  \
0                                                NaN                      NaN
1                                                NaN                      NaN
2                                                NaN                      NaN
3                                                NaN                      NaN
4                                                NaN                      NaN

  player.injury.status player.injury.id player.injury.startDateTimestamp  \
0                  NaN              NaN                              NaN
1                  NaN              NaN                              NaN
2                  NaN              NaN                              NaN
3                  NaN              NaN                              NaN
4                  NaN              NaN                              NaN

   player.injury.updateDateTimestamp  player.injury.endDateTimestamp  \
0                                NaN                             NaN
1                                NaN                             NaN
2                                NaN                             NaN
3                                NaN                             NaN
4                                NaN                             NaN

  player.retired
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN

[5 rows x 236 columns]

In [111]:
df6 = pd.DataFrame(df_previous)
df6

,transferDate,player.name,player.slug,player.shortName,player.team.name,player.team.slug,player.team.shortName,player.team.gender,player.team.sport.name,player.team.sport.slug,...,previousTeam.fieldTranslations.shortNameTranslation.hi,player.firstName,previousTeam.fieldTranslations.shortNameTranslation.bn,player.injury.reason,player.injury.status,player.injury.id,player.injury.startDateTimestamp,player.injury.updateDateTimestamp,player.injury.endDateTimestamp,player.retired
0,2026-06-30T00:00:00+00:00,Mario Martín,martin-mario,M. Martín,Getafe,getafe,Getafe,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-08-14T00:00:00+00:00,Franco Mastantuono,franco-mastantuono,F. Mastantuono,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,रिवर,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-07-14T00:00:00+00:00,Álvaro Carreras,alvaro-carreras,Á. Carreras,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-07-01T00:00:00+00:00,Gonzalo García,gonzalo-garcia,G. García,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,Gonzalo García,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-06-01T00:00:00+00:00,Dean Huijsen,dean-huijsen,D. Huijsen,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2025-06-01T00:00:00+00:00,Trent Alexander-Arnold,trent-alexander-arnold,T. Alexander-Arnold,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2024-07-21T00:00:00+00:00,Endrick,endrick,Endrick,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-07-01T00:00:00+00:00,Raúl Asencio,raul-asencio,R. Asencio,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024-07-01T00:00:00+00:00,Kylian Mbappé,kylian-mbappe,K. Mbappé,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,पीएसजी,NaN,পিএসজি,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2023-07-06T00:00:00+00:00,Arda Güler,arda-guler,A. Güler,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,Arda Guler,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2023-07-01T00:00:00+00:00,Jude Bellingham,jude-bellingham,J. Bellingham,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,डॉर्टमुंड,NaN,ডর্টমুন্ড,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2023-07-01T00:00:00+00:00,Fran García,fran-garcia,F. Garcia,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2023-06-30T00:00:00+00:00,Brahim Díaz,brahim-diaz,B. Díaz,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2022-07-01T00:00:00+00:00,Aurélien Tchouaméni,aurelien-tchouameni,A. Tchouaméni,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2022-07-01T00:00:00+00:00,Antonio Rüdiger,antonio-rudiger,A. Rüdiger,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,Thigh Injury,out,4611.0,1.757635e+09,1.762085e+09,1.765152e+09,NaN
15,2021-08-31T00:00:00+00:00,Eduardo Camavinga,camavinga-eduardo,E. Camavinga,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,रेनेस,NaN,রেনাইস,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-07-01T00:00:00+00:00,David Alaba,david-alaba,D. Alaba,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,बायर्न,NaN,বায়ার্ন,Calf Injury,out,9247.0,1.760918e+09,1.762085e+09,1.762301e+09,NaN
17,2021-06-30T00:00:00+00:00,Dani Ceballos,dani-ceballos,D. Ceballos,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2020-07-21T00:00:00+00:00,Andriy Lunin,andriy-lunin,A. Lunin,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
19,2019-07-01T00:00:00+00:00,Rodrygo,rodrygo,Rodrygo,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2019-07-01T00:00:00+00:00,Éder Militão,eder-militao,É. Militão,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,पोर्तो,NaN,পোর্তো,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2019-07-01T00:00:00+00:00,Ferland Mendy,ferland-mendy,F. Mendy,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,लियोन,NaN,লিওন,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2018-08-09T00:00:00+00:00,Thibaut Courtois,thibaut-courtois,T. Courtois,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2018-07-12T00:00:00+00:00,Vinícius Júnior,vinicius-junior,Vinícius Jr.,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2018-07-01T00:00:00+00:00,Federico Valverde,federico-valverde,F. Valverde,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2013-07-01T00:00:00+00:00,Daniel Carvajal,daniel-carvajal,D. Carvajal,Real Madrid,real-madrid,Real Madrid,M,Football,football,...,लेवरकुसेन,NaN,লেভারকুসেন,Knee Injury,dayToDay,9817.0,1.761523e+09,1.762085e+09,1.767917e+09,NaN

In [112]:
df_statistics= pd.json_normalize(data2['nationalTeamPlayerStatistics'])
print("\nnational Team Player Statistics:")
print(df_statistics.head())

national Team Player Statistics:
Empty DataFrame
Columns: []
Index: []

# **Scrapping Last Events**

In [115]:
url = "http://footballapi.eastus.azurecontainer.io:3000/teams/2829/events/last/0"

In [116]:
response = requests.get(url)
data3 = response.json()

In [117]:
print(data3)

{'events': [{'tournament': {'name': 'UEFA Champions League, Knockout Phase', 'slug': 'uefa-champions-league-knockout-phase', 'category': {'name': 'Europe', 'slug': 'europe', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 1465, 'country': {}, 'flag': 'europe', 'fieldTranslations': {'nameTranslation': {'ar': 'أوروبا', 'hi': 'यूरोप', 'bn': 'ইউরোপ'}, 'shortNameTranslation': {}}}, 'uniqueTournament': {'name': 'UEFA Champions League', 'slug': 'uefa-champions-league', 'primaryColorHex': '#062b5c', 'secondaryColorHex': '#086aab', 'category': {'name': 'Europe', 'slug': 'europe', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 1465, 'country': {}, 'flag': 'europe', 'fieldTranslations': {'nameTranslation': {'ar': 'أوروبا', 'hi': 'यूरोप', 'bn': 'ইউরোপ'}, 'shortNameTranslation': {}}}, 'userCount': 1222580, 'hasPerformanceGraphFeature': False, 'id': 7, 'country': {}, 'hasEventPlayerStatistics': True, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'دوري أبطال أوروبا', 'hi': 'यूईएफए चैंपियंस लीग', 'bn': 'উয়েফা চ্যাম্পিয়ন্স লীগ'}, 'shortNameTranslation': {}}}, 'priority': 697, 'isGroup': False, 'id': 145109, 'fieldTranslations': {'nameTranslation': {'ar': 'دوري أبطال أوروبا، مرحلة خروج المغلوب'}, 'shortNameTranslation': {}}}, 'season': {'name': 'UEFA Champions League 24/25', 'year': '24/25', 'editor': False, 'seasonCoverageInfo': {}, 'id': 61644}, 'roundInfo': {'round': 27, 'name': 'Quarterfinals', 'slug': 'quarterfinals', 'cupRoundType': 4}, 'customId': 'RsEgb', 'status': {'code': 100, 'description': 'Ended', 'type': 'finished'}, 'winnerCode': 2, 'aggregatedWinnerCode': 2, 'homeTeam': {'name': 'Real Madrid', 'slug': 'real-madrid', 'shortName': 'Real Madrid', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 6117089, 'nameCode': 'RMA', 'disabled': False, 'national': False, 'type': 0, 'id': 2829, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'subTeams': [], 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'ru': 'Реал Мадрид', 'hi': 'रियल मैड्रिड', 'bn': 'রিয়াল মাদ্রিদ'}, 'shortNameTranslation': {}}}, 'awayTeam': {'name': 'Arsenal', 'slug': 'arsenal', 'shortName': 'Arsenal', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 2765401, 'nameCode': 'ARS', 'disabled': False, 'national': False, 'type': 0, 'id': 42, 'country': {'alpha2': 'EN', 'alpha3': 'ENG', 'name': 'England', 'slug': 'england'}, 'subTeams': [], 'teamColors': {'primary': '#cc0000', 'secondary': '#ffffff', 'text': '#ffffff'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ارسنال', 'ru': 'Арсенал', 'hi': 'आर्सेनल', 'bn': 'আর্সেনাল'}, 'shortNameTranslation': {}}}, 'homeScore': {'current': 1, 'display': 1, 'period1': 0, 'period2': 1, 'normaltime': 1, 'aggregated': 1}, 'awayScore': {'current': 2, 'display': 2, 'period1': 0, 'period2': 2, 'normaltime': 2, 'aggregated': 5}, 'time': {'injuryTime1': 7, 'injuryTime2': 5, 'currentPeriodStartTimestamp': 1744834207}, 'changes': {'changes': ['status.code', 'status.description', 'status.type', 'awayScore.period2', 'awayScore.normaltime'], 'changeTimestamp': 1744837250}, 'hasGlobalHighlights': True, 'hasXg': True, 'hasEventPlayerStatistics': True, 'hasEventPlayerHeatMap': True, 'detailId': 1, 'crowdsourcingDataDisplayEnabled': False, 'id': 13513422, 'varInProgress': {'homeTeam': False, 'awayTeam': False}, 'slug': 'real-madrid-arsenal', 'previousLegEventId': 13513403, 'startTimestamp': 1744830000, 'finalResultOnly': False, 'feedLocked': True, 'isEditor': False}, {'tournament': {'name': 'LaLiga', 'slug': 'laliga', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'uniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'hasPerformanceGraphFeature': True, 'id': 8, 'country': {}, 'hasEventPlayerStatistics': True, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'priority': 691, 'isGroup': False, 'isLive': False, 'id': 36, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लीगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'season': {'name': 'LaLiga 24/25', 'year': '24/25', 'editor': False, 'id': 61643}, 'roundInfo': {'round': 32}, 'customId': 'AgbsEgb', 'status': {'code': 100, 'description': 'Ended', 'type': 'finished'}, 'winnerCode': 1, 'homeTeam': {'name': 'Real Madrid', 'slug': 'real-madrid', 'shortName': 'Real Madrid', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 6117089, 'nameCode': 'RMA', 'disabled': False, 'national': False, 'type': 0, 'id': 2829, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'subTeams': [], 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'ru': 'Реал Мадрид', 'hi': 'रियल मैड्रिड', 'bn': 'রিয়াল মাদ্রিদ'}, 'shortNameTranslation': {}}}, 'awayTeam': {'name': 'Athletic Club', 'slug': 'athletic-club', 'shortName': 'Athletic Club', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 568316, 'nameCode': 'ATH', 'disabled': False, 'national': False, 'type': 0, 'id': 2825, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'subTeams': [], 'teamColors': {'primary': '#aa0000', 'secondary': '#ffffff', 'text': '#ffffff'}, 'fieldTranslations': {'nameTranslation': {'ar': 'نادي أتليتيك', 'ru': 'Атлетик Бильбао', 'hi': 'एथलेटिक क्लब', 'bn': 'অ্যাথলেটিক ক্লাব'}, 'shortNameTranslation': {}}}, 'homeScore': {'current': 1, 'display': 1, 'period1': 0, 'period2': 1, 'normaltime': 1}, 'awayScore': {'current': 0, 'display': 0, 'period1': 0, 'period2': 0, 'normaltime': 0}, 'time': {'injuryTime1': 0, 'injuryTime2': 7, 'currentPeriodStartTimestamp': 1745179302}, 'changes': {'changes': ['time.injuryTime2', 'status.code', 'status.description', 'status.type'], 'changeTimestamp': 1745182498}, 'hasGlobalHighlights': True, 'hasXg': True, 'hasEventPlayerStatistics': True, 'hasEventPlayerHeatMap': True, 'detailId': 1, 'crowdsourcingDataDisplayEnabled': False, 'id': 12437523, 'varInProgress': {'homeTeam': False, 'awayTeam': False}, 'slug': 'real-madrid-athletic-club', 'startTimestamp': 1745175600, 'finalResultOnly': False, 'feedLocked': True, 'isEditor': False}, {'correctAiInsight': True, 'tournament': {'name': 'LaLiga', 'slug': 'laliga', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'uniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'hasPerformanceGraphFeature': True, 'id': 8, 'country': {}, 'hasEventPlayerStatistics': True, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'priority': 691, 'isGroup': False, 'isLive': False, 'id': 36, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लीगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'season': {'name': 'LaLiga 24/25', 'year': '24/25', 'editor': False, 'id': 61643}, 'roundInfo': {'round': 33}, 'customId': 'Egbsjhb', 'status': {'code': 100, 'description': 'Ended', 'type': 'finished'}, 'winnerCode': 2, 'homeTeam': {'name': 'Getafe', 'slug': 'getafe', 'shortName': 'Getafe', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 202151, 'nameCode': 'GET', 'disabled': False, 'national': False, 'type': 0, 'id': 2859, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'subTeams': [], 'teamColors': {'primary': '#00369e', 'secondary': '#ffffff', 'text': '#ffffff'}, 'fieldTranslations': {'nameTranslation': {'ar': 'خيتافي', 'ru': 'Хетафе', 'hi': 'गेटाफे', 'bn': 'গেটাফে'}, 'shortNameTranslation': {}}}, 'awayTeam': {'name': 'Real Madrid', 'slug': 'real-madrid', 'shortName': 'Real Madrid', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 6117089, 'nameCode': 'RMA', 'disabled': False, 'national': False, 'type': 0, 'id': 2829, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'subTeams': [], 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'ru': 'Реал Мадрид', 'hi': 'रियल मैड्रिड', 'bn': 'রিয়াল মাদ্রিদ'}, 'shortNameTranslation': {}}}, 'homeScore': {'current': 0, 'display': 0, 'period1': 0, 'period2': 0, 'normaltime': 0}, 'awayScore': {'current': 1, 'display': 1, 'period1': 1, 'period2': 0, 'normaltime': 1}, 'time': {'injuryTime1': 2, 'injuryTime2': 6, 'currentPeriodStartTimestamp': 1745440578}, 'changes': {'changes': ['status.code', 'status.description', 'status.type'], 'changeTimestamp': 1745443696}, 'hasGlobalHighlights': True, 'hasXg': True, 'hasEventPlayerStatistics': True, 'hasEventPlayerHeatMap': True, 'detailId': 1, 'crowdsourcingDataDisplayEnabled': False, 'id': 12437530, 'varInProgress': {'homeTeam': False, 'awayTeam': False}, 'slug': 'getafe-real-madrid', 'startTimestamp': 1745436600, 'finalResultOnly': False, 'feedLocked': True, 'isEditor': False}, {'correctAiInsight': False, 'tournament': {'name': 'Copa del Rey', 'slug': 'copa-del-rey', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'uniqueTournament': {'name': 'Copa del Rey', 'slug': 'copa-del-rey', 'primaryColorHex': '#221C35', 'secondaryColorHex': '#fe0235', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 171818, 'hasPerformanceGraphFeature': False, 'id': 329, 'country': {}, 'hasEventPlayerStatistics': False, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'كأس ملك إسبانيا', 'hi': 'कोपा डेल रे', 'bn': 'কোপা দেল রে'}, 'shortNameTranslation': {}}}, 'priority': 687, 'isGroup': False, 'isLive': False, 'id': 150, 'fieldTranslations': {'nameTranslation': {'ar': 'كأس إسبانيا', 'hi': 'कोपा डेल रे', 'bn': 'কোপা দেল রে'}, 'shortNameTranslation': {}}}, 'season': {'name': 'Copa del Rey 24/25', 'year': '24/25', 'editor': False, 'seasonCoverageInfo': {'editorCoverageLevel': 1}, 'id': 66885}, 'roundInfo': {'round': 29, 'name': 'Final', 'slug': 'final', 'cupRoundType': 1}, 'customId': 'rgbsEgb', 'status': {'code': 110, 'description': 'AET', 'type': 'finished'}, 'winnerCode': 1, 'homeTeam': {'name': 'Barcelona', 'slug': 'barcelona', 'shortName': 'Barcelona', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 5659422, 'nameCode': 'BAR', 'disabled': False, 'national': False, 'type': 0, 'id': 2817, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'subTeams': [], 'teamColors': {'primary': '#154284', 'secondary': '#9d1009', 'text': '#9d1009'}, 'fieldTranslations': {'nameTranslation': {'ar': 'برشلونة', 'ru': 'Барселона', 'hi': 'बार्सिलोना', 'bn': 'বার্সেলোনা'}, 'shortNameTranslation': {}}}, 'awayTeam': {'name': 'Real Madrid', 'slug': 'real-madrid', 'shortName': 'Real Madrid', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 6117089, 'nameCode': 'RMA', 'disabled': False, 'national': False, 'type': 0, 'id': 2829, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'subTeams': [], 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'ru': 'Реал Мадрид', 'hi': 'रियल मैड्रिड', 'bn': 'রিয়াল মাদ্রিদ'}, 'shortNameTranslation': {}}}, 'homeScore': {'current': 3, 'display': 3, 'period1': 1, 'period2': 1, 'normaltime': 2, 'extra1': 0, 'extra2': 1, 'overtime': 1}, 'awayScore': {'current': 2, 'display': 2, 'period1': 0, 'period2': 2, 'normaltime': 2, 'extra1': 0, 'extra2': 0, 'overtime': 0}, 'time': {'injuryTime1': 5, 'injuryTime2': 6, 'injuryTime3': 0, 'injuryTime4': 2, 'currentPeriodStartTimestamp': 1745706444}, 'changes': {'changes': ['cardsCode'], 'changeTimestamp': 1746107593}, 'hasGlobalHighlights': True, 'hasEventPlayerStatistics': True, 'hasEventPlayerHeatMap': True, 'detailId': 1, 'crowdsourcingDataDisplayEnabled': False, 'id': 13708595, 'awayRedCards': 1, 'varInProgress': {'homeTeam': False, 'awayTeam': False}, 'slug': 'real-madrid-barcelona', 'startTimestamp': 1745697600, 'finalResultOnly': False, 'feedLocked': True, 'isEditor': False}, {'correctAiInsight': True, 'tournament': {'name': 'LaLiga', 'slug': 'laliga', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'uniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'hasPerformanceGraphFeature': True, 'id': 8, 'country': {}, 'hasEventPlayerStatistics': True, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'priority': 691, 'isGroup': False, 'isLive': False, 'id': 36, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लीगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'season': {'name': 'LaLiga 24/25', 'year': '24/25', 'editor': False, 'id': 61643}, 'roundInfo': {'round': 34}, 'customId': 'wgbsEgb', 'status': {'code': 100, 'description': 'Ended', 'type': 'finished'}, 'winnerCode': 1, 'homeTeam': {'name': 'Real Madrid', 'slug': 'real-madrid', 'shortName': 'Real Madrid', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 6117089, 'nameCode': 'RMA', 'disabled': False, 'national': False, 'type': 0, 'id': 2829, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'subTeams': [], 'teamColors': {'primary': '#ffffff', 'secondary': '#004996', 'text': '#004996'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريال مدريد', 'ru': 'Реал Мадрид', 'hi': 'रियल मैड्रिड', 'bn': 'রিয়াল মাদ্রিদ'}, 'shortNameTranslation': {}}}, 'awayTeam': {'name': 'Celta Vigo', 'slug': 'celta-vigo', 'shortName': 'Celta', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 226543, 'nameCode': 'CVI', 'disabled': False, 'national': False, 'type': 0, 'id': 2821, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'subTeams': [], 'teamColors': {'primary': '#6cace4', 'secondary': '#ffffff', 'text': '#ffffff'}, 'fieldTranslations': {'nameTranslation': {'ar': 'سيلتا فيغو', 'ru': 'Сельта', 'bn': 'সেলটা ভিগো'}, 'shortNameTranslation': {'ar': 'سيلتا', 'hi': 'सेल्टा'}}}, 'homeScore': {'current': 3, 'display': 3, 'period1': 2, 'period2': 1, 'normaltime': 3}, 'awayScore': {'current': 2, 'display': 2, 'period1': 0, 'period2': 2, 'normaltime': 2}, 'time': {'injuryTime1': 2, 'injuryTime2': 5, 'currentPeriodStartTimestamp': 1746363875}, 'changes': {'changes': ['status.code', 'status.description', 'status.type'], 'changeTimestamp': 1746366889}, 'hasGlobalHighlights': True, 'hasXg': True, 'hasEventPlayerStatistics': True, 'hasEventPlayerHeatMap': True, 'detailId': 1, 'crowdsourcingDataDisplayEnabled': False, 'id': 12437532, 'varInProgress': {'homeTeam': False, 'awayTeam': False}, 'slug': 'real-madrid-celta-vigo', 'startTimestamp': 1746360000, 'finalResultOnly': False, 'feedLocked': True, 'isEditor': False}, {'correctAiInsight': True, 'tournament': {'name': 'LaLiga', 'slug': 'laliga', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'uniqueTournament': {'name': 'LaLiga', 'slug': 'laliga', 'primaryColorHex': '#2f4a89', 'secondaryColorHex': '#f4a32e', 'category': {'name': 'Spain', 'slug': 'spain', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 32, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'flag': 'spain', 'alpha2': 'ES', 'fieldTranslations': {'nameTranslation': {'ar': 'إسبانيا', 'hi': 'स्पेन', 'bn': 'স্পেন'}, 'shortNameTranslation': {}}}, 'userCount': 875455, 'hasPerformanceGraphFeature': True, 'id': 8, 'country': {}, 'hasEventPlayerStatistics': True, 'displayInverseHomeAwayTeams': False, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लिगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'priority': 691, 'isGroup': False, 'isLive': False, 'id': 36, 'fieldTranslations': {'nameTranslation': {'ar': 'الدوري الإسباني', 'hi': 'ला लीगा', 'bn': 'লা লীগা'}, 'shortNameTranslation': {}}}, 'season': {'name': 'LaLiga 24/25', 'year': '24/25', 'editor': False, 'id': 61643}, 'roundInfo': {'round': 35}, 'customId': 'rgbsEgb', 'status': {'code': 100, 'description': 'Ended', 'type': 'finished'}, 'winnerCode': 1, 'homeTeam': {'name': 'Barcelona', 'slug': 'barcelona', 'shortName': 'Barcelona', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 5659422, 'nameCode': 'BAR', 'disabled': False, 'national': False, 'type': 0, 'id': 2817, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'subTeams': [], 'teamColors': {'primary': '#15

In [118]:
print(type(data3))

<class 'dict'>

In [127]:
print(data3.keys())

dict_keys(['events', 'hasNextPage'])

In [164]:
df_ev = pd.DataFrame(data3)
df_ev

                                               events  hasNextPage
0   {'tournament': {'name': 'UEFA Champions League...         True
1   {'tournament': {'name': 'LaLiga', 'slug': 'lal...         True
2   {'correctAiInsight': True, 'tournament': {'nam...         True
3   {'correctAiInsight': False, 'tournament': {'na...         True
4   {'correctAiInsight': True, 'tournament': {'nam...         True
5   {'correctAiInsight': True, 'tournament': {'nam...         True
6   {'correctAiInsight': True, 'tournament': {'nam...         True
7   {'correctAiInsight': True, 'tournament': {'nam...         True
8   {'correctAiInsight': True, 'tournament': {'nam...         True
9   {'correctAiInsight': False, 'tournament': {'na...         True
10  {'correctAiInsight': True, 'tournament': {'nam...         True
11  {'correctAiInsight': True, 'correctHalftimeAiI...         True
12  {'correctAiInsight': True, 'correctHalftimeAiI...         True
13  {'correctAiInsight': True, 'correctHalftimeAiI...         True
14  {'correctAiInsight': False, 'correctHalftimeAi...         True
15  {'tournament': {'name': 'Club Friendly Games',...         True
16  {'correctAiInsight': True, 'correctHalftimeAiI...         True
17  {'correctAiInsight': True, 'correctHalftimeAiI...         True
18  {'correctAiInsight': True, 'correctHalftimeAiI...         True
19  {'correctAiInsight': True, 'correctHalftimeAiI...         True
20  {'correctAiInsight': True, 'correctHalftimeAiI...         True
21  {'correctAiInsight': True, 'correctHalftimeAiI...         True
22  {'correctAiInsight': True, 'correctHalftimeAiI...         True
23  {'correctAiInsight': False, 'correctHalftimeAi...         True
24  {'correctAiInsight': True, 'correctHalftimeAiI...         True
25  {'correctAiInsight': True, 'correctHalftimeAiI...         True
26  {'correctAiInsight': True, 'correctHalftimeAiI...         True
27  {'correctAiInsight': True, 'correctHalftimeAiI...         True
28  {'correctAiInsight': True, 'correctHalftimeAiI...         True
29  {'correctAiInsight': True, 'correctHalftimeAiI...         True

In [165]:
df_events = pd.json_normalize(df_ev['events'])
df_events['hasNextPage'] = df_ev['hasNextPage']
df_events

,customId,winnerCode,aggregatedWinnerCode,hasGlobalHighlights,hasXg,hasEventPlayerStatistics,hasEventPlayerHeatMap,detailId,crowdsourcingDataDisplayEnabled,id,...,homeRedCards,coverage,tournament.groupName,tournament.groupSign,correctHalftimeAiInsight,homeTeam.fieldTranslations.shortNameTranslation.ar,homeTeam.fieldTranslations.shortNameTranslation.hi,homeTeam.fieldTranslations.shortNameTranslation.bn,awayTeam.fieldTranslations.shortNameTranslation.bn,hasNextPage
0,RsEgb,2,2.0,True,True,True,True,1,False,13513422,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,AgbsEgb,1,NaN,True,True,True,True,1,False,12437523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,Egbsjhb,2,NaN,True,True,True,True,1,False,12437530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,rgbsEgb,1,NaN,True,NaN,True,True,1,False,13708595,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4,wgbsEgb,1,NaN,True,True,True,True,1,False,12437532,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
5,rgbsEgb,1,NaN,True,True,True,True,1,False,12437545,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
6,BgbsEgb,1,NaN,True,True,True,True,1,False,12437491,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
7,EgbsIgb,2,NaN,True,True,True,True,1,False,12437499,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
8,zgbsEgb,1,NaN,True,True,True,True,1,False,12437506,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
9,EgbsVMi,3,NaN,False,NaN,True,True,1,False,13200270,...,NaN,-1.0,Group H,H,NaN,NaN,NaN,NaN,NaN,True
10,LNsEgb,1,NaN,False,NaN,True,True,1,False,13200297,...,1.0,-1.0,Group H,H,NaN,NaN,NaN,NaN,NaN,True
11,WPsEgb,2,NaN,False,NaN,True,True,1,False,13200233,...,NaN,-1.0,Group H,H,True,إر بي سالزبورغ,आरबी साल्ज़बर्ग,আরবি সালজবার্গ,NaN,True
12,MdbsEgb,1,NaN,False,NaN,True,True,1,False,13385908,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True
13,ydbsEgb,1,NaN,False,NaN,True,True,1,False,13385891,...,1.0,NaN,NaN,NaN,True,NaN,NaN,NaN,ডর্টমুন্ড,True
14,UHsEgb,1,NaN,False,NaN,True,True,1,False,13385902,...,NaN,NaN,NaN,NaN,True,NaN,पीएसजी,পিএসজি,NaN,True
15,Egbsfic,2,NaN,False,NaN,True,True,1,False,14349910,...,NaN,NaN,NaN,NaN,NaN,تيرول,टिरोल,তিরোল,NaN,True
16,vgbsEgb,1,NaN,True,True,True,True,1,False,14082856,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True
17,Egbsbhb,2,NaN,True,True,True,True,1,False,14082862,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True
18,BgbsEgb,1,NaN,True,True,True,True,1,False,14083197,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True
19,zgbsEgb,2,NaN,True,True,True,True,1,False,14083256,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True
20,QHsEgb,1,NaN,True,True,True,True,1,False,14566597,...,1.0,-1.0,NaN,NaN,True,NaN,NaN,NaN,মার্সেই,True
21,ogbsEgb,1,NaN,True,True,True,True,1,False,14083333,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True
22,EgbsZgb,2,NaN,True,True,True,True,1,False,14083426,...,NaN,NaN,NaN,NaN,True,ليفانتي,लेवांते,লেভান্তে,NaN,True
23,EgbsLgb,1,NaN,True,True,True,True,1,False,14083541,...,NaN,NaN,NaN,NaN,True,أتل. مدريد,NaN,এটিএল. মাদ্রিদ,NaN,True
24,Egbsxdc,2,NaN,True,True,True,True,1,False,14566983,...,NaN,-1.0,NaN,NaN,True,كايرات,कैरात,কাইরাত,NaN,True
25,ugbsEgb,1,NaN,True,True,True,True,1,False,14083620,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True
26,Egbsjhb,2,NaN,True,True,True,True,1,False,14083675,...,2.0,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True
27,MdbsEgb,1,NaN,True,True,True,True,1,False,14566596,...,NaN,-1.0,NaN,NaN,True,NaN,NaN,NaN,NaN,True
28,rgbsEgb,1,NaN,True,True,True,True,1,False,14083729,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True
29,DgbsEgb,1,NaN,True,True,True,True,1,False,14083099,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,True

In [166]:
df_events.columns

Index(['customId', 'winnerCode', 'aggregatedWinnerCode', 'hasGlobalHighlights',
       'hasXg', 'hasEventPlayerStatistics', 'hasEventPlayerHeatMap',
       'detailId', 'crowdsourcingDataDisplayEnabled', 'id',
       ...
       'homeRedCards', 'coverage', 'tournament.groupName',
       'tournament.groupSign', 'correctHalftimeAiInsight',
       'homeTeam.fieldTranslations.shortNameTranslation.ar',
       'homeTeam.fieldTranslations.shortNameTranslation.hi',
       'homeTeam.fieldTranslations.shortNameTranslation.bn',
       'awayTeam.fieldTranslations.shortNameTranslation.bn', 'hasNextPage'],
      dtype='object', length=170)

# **Scrapping Events/Lineups**

In [79]:
url = "http://footballapi.eastus.azurecontainer.io:3000/events/12436594/lineups"

In [80]:
response = requests.get(url)
data4 = response.json()

In [81]:
print(data4)

{'confirmed': True, 'home': {'players': [{'player': {'name': 'Ederson', 'slug': 'ederson', 'shortName': 'Ederson', 'position': 'G', 'jerseyNumber': '31', 'height': 188, 'userCount': 56148, 'gender': 'M', 'sofascoreId': 'Ederson93', 'id': 254491, 'country': {'alpha2': 'BR', 'alpha3': 'BRA', 'name': 'Brazil', 'slug': 'brazil'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 745545600, 'proposedMarketValueRaw': {'value': 16600000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'إيدرسون', 'hi': 'एडरसन', 'bn': 'এডারসন'}, 'shortNameTranslation': {'ar': 'إيدرسون', 'hi': 'एडरसन', 'bn': 'এডারসন'}}}, 'teamId': 3052, 'shirtNumber': 31, 'jerseyNumber': '31', 'position': 'G', 'substitute': False, 'statistics': {'totalPass': 24, 'accuratePass': 24, 'totalLongBalls': 3, 'accurateLongBalls': 3, 'goalAssist': 0, 'accurateOwnHalfPasses': 24, 'totalOwnHalfPasses': 24, 'totalClearance': 1, 'ballRecovery': 7, 'totalKeeperSweeper': 1, 'accurateKeeperSweeper': 1, 'minutesPlayed': 90, 'touches': 27, 'rating': 6.9, 'expectedAssists': 0.00011822, 'ratingVersions': {'original': 6.9, 'alternative': 6.9}, 'totalShots': 0}}, {'player': {'name': 'Matheus Nunes', 'firstName': '', 'lastName': '', 'slug': 'matheus-nunes', 'shortName': 'M. Nunes', 'position': 'D', 'jerseyNumber': '27', 'height': 183, 'userCount': 18417, 'gender': 'M', 'sofascoreId': 'matheusnunes', 'id': 945122, 'country': {'alpha2': 'PT', 'alpha3': 'PRT', 'name': 'Portugal', 'slug': 'portugal'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 904176000, 'proposedMarketValueRaw': {'value': 33000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ماثيوس نونيز', 'hi': 'मैथियस नून्स', 'bn': 'ম্যাথিউস নুনেস'}, 'shortNameTranslation': {'ar': 'م. نونيز', 'hi': 'एम. नून्स', 'bn': 'এম. নুনেস'}}}, 'teamId': 17, 'shirtNumber': 27, 'jerseyNumber': '27', 'position': 'D', 'substitute': False, 'statistics': {'totalPass': 103, 'accuratePass': 97, 'totalLongBalls': 1, 'accurateLongBalls': 1, 'goalAssist': 0, 'accurateOwnHalfPasses': 26, 'totalOwnHalfPasses': 27, 'accurateOppositionHalfPasses': 71, 'totalOppositionHalfPasses': 76, 'aerialLost': 1, 'duelLost': 3, 'duelWon': 2, 'totalContest': 3, 'wonContest': 2, 'ballRecovery': 3, 'unsuccessfulTouch': 2, 'fouls': 2, 'minutesPlayed': 90, 'touches': 114, 'rating': 7.3, 'possessionLostCtrl': 9, 'expectedAssists': 0.0962931, 'ratingVersions': {'original': 7.3, 'alternative': 7}, 'totalShots': 0}}, {'player': {'name': 'Rúben Dias', 'firstName': '', 'lastName': '', 'slug': 'ruben-dias', 'shortName': 'R. Dias', 'position': 'D', 'jerseyNumber': '3', 'height': 188, 'userCount': 42944, 'gender': 'M', 'sofascoreId': 'RúbenD', 'id': 318941, 'country': {'alpha2': 'PT', 'alpha3': 'PRT', 'name': 'Portugal', 'slug': 'portugal'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 863568000, 'proposedMarketValueRaw': {'value': 65000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'روبن دياز', 'hi': 'रुबेन डियास', 'bn': 'রুবেন ডায়াস'}, 'shortNameTranslation': {'ar': 'ر. دياز', 'hi': 'आर. डियास', 'bn': 'আর. ডায়াস'}}}, 'teamId': 17, 'shirtNumber': 3, 'jerseyNumber': '3', 'position': 'D', 'substitute': False, 'captain': True, 'statistics': {'totalPass': 128, 'accuratePass': 123, 'totalLongBalls': 5, 'accurateLongBalls': 2, 'goalAssist': 0, 'accurateOwnHalfPasses': 44, 'totalOwnHalfPasses': 44, 'accurateOppositionHalfPasses': 79, 'totalOppositionHalfPasses': 84, 'aerialWon': 2, 'duelWon': 2, 'totalClearance': 2, 'ballRecovery': 3, 'unsuccessfulTouch': 1, 'minutesPlayed': 90, 'touches': 133, 'rating': 7.5, 'possessionLostCtrl': 6, 'expectedAssists': 0.0439067, 'ratingVersions': {'original': 7.5, 'alternative': 7.8}, 'totalShots': 0}}, {'player': {'name': 'Joško Gvardiol', 'slug': 'josko-gvardiol', 'shortName': 'J. Gvardiol', 'position': 'D', 'jerseyNumber': '24', 'height': 186, 'userCount': 53585, 'gender': 'M', 'sofascoreId': 'JGvardiol', 'id': 964994, 'country': {'alpha2': 'HR', 'alpha3': 'HRV', 'name': 'Croatia', 'slug': 'croatia'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 1011744000, 'proposedMarketValueRaw': {'value': 69000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'يوشكو غفارديول', 'hi': 'जोस्को ग्वार्डिओल', 'bn': 'জোসকো গোওয়ারদিওল'}, 'shortNameTranslation': {'ar': 'ي. غفارديول', 'hi': 'जे. ग्वार्डिओल', 'bn': 'জে. গোওয়ারদিওল'}}}, 'teamId': 17, 'shirtNumber': 24, 'jerseyNumber': '24', 'position': 'D', 'substitute': False, 'statistics': {'totalPass': 111, 'accuratePass': 110, 'totalLongBalls': 2, 'accurateLongBalls': 2, 'goalAssist': 0, 'accurateOwnHalfPasses': 45, 'totalOwnHalfPasses': 45, 'accurateOppositionHalfPasses': 65, 'totalOppositionHalfPasses': 66, 'aerialLost': 1, 'duelLost': 2, 'duelWon': 1, 'dispossessed': 1, 'blockedScoringAttempt': 1, 'totalClearance': 3, 'ballRecovery': 2, 'lastManTackle': 1, 'totalTackle': 1, 'wonTackle': 1, 'unsuccessfulTouch': 1, 'minutesPlayed': 89, 'touches': 120, 'rating': 7.6, 'possessionLostCtrl': 3, 'expectedGoals': 0.0535, 'expectedAssists': 0.185108, 'keyPass': 1, 'ratingVersions': {'original': 7.6, 'alternative': 8.2}, 'totalShots': 1}}, {'player': {'name': "Nico O'Reilly", 'firstName': 'Nico', 'lastName': 'O’Reilly', 'slug': 'nico-o-reilly', 'shortName': 'N. O’Reilly', 'position': 'D', 'jerseyNumber': '33', 'height': 193, 'userCount': 10937, 'gender': 'M', 'id': 1142703, 'country': {'alpha2': 'EN', 'alpha3': 'ENG', 'name': 'England', 'slug': 'england'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 1111363200, 'proposedMarketValueRaw': {'value': 32000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'نيكو أوريلي', 'hi': "निको ओ'रेली", 'bn': "নিকো ও'রেইলি"}, 'shortNameTranslation': {'ar': 'ن. أوريلي', 'hi': "एन. ओ'रेली", 'bn': "এন. ও'রেইলি"}}}, 'teamId': 17, 'shirtNumber': 75, 'jerseyNumber': '75', 'position': 'D', 'substitute': False, 'statistics': {'totalPass': 73, 'accuratePass': 64, 'totalLongBalls': 2, 'accurateLongBalls': 1, 'goalAssist': 0, 'accurateOwnHalfPasses': 23, 'totalOwnHalfPasses': 26, 'accurateOppositionHalfPasses': 41, 'totalOppositionHalfPasses': 47, 'aerialLost': 2, 'aerialWon': 2, 'duelLost': 4, 'duelWon': 7, 'challengeLost': 1, 'totalContest': 3, 'wonContest': 3, 'blockedScoringAttempt': 1, 'totalClearance': 3, 'interceptionWon': 1, 'ballRecovery': 2, 'totalTackle': 1, 'unsuccessfulTouch': 2, 'wasFouled': 1, 'fouls': 1, 'minutesPlayed': 90, 'touches': 90, 'rating': 7.7, 'possessionLostCtrl': 13, 'expectedGoals': 0.1118, 'expectedAssists': 0.0390558, 'keyPass': 1, 'ratingVersions': {'original': 7.7, 'alternative': 6.7}, 'totalShots': 1}}, {'player': {'name': 'Nico González', 'firstName': '', 'lastName': '', 'slug': 'nico-gonzalez', 'shortName': 'N. González', 'position': 'M', 'jerseyNumber': '14', 'height': 186, 'userCount': 15400, 'gender': 'M', 'sofascoreId': 'nico14', 'id': 954056, 'country': {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'slug': 'spain'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 1010016000, 'proposedMarketValueRaw': {'value': 43000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'نيكولاس غونزاليس', 'hi': 'निकोलस गोंजालेज', 'bn': 'নিকোলাস গঞ্জালেজ'}, 'shortNameTranslation': {'ar': 'ن. غونزاليس', 'hi': 'एन. गोंजालेज', 'bn': 'এন. গঞ্জালেজ'}}}, 'teamId': 17, 'shirtNumber': 14, 'jerseyNumber': '14', 'position': 'M', 'substitute': False, 'statistics': {'totalPass': 72, 'accuratePass': 69, 'totalLongBalls': 1, 'goalAssist': 0, 'accurateOwnHalfPasses': 18, 'totalOwnHalfPasses': 18, 'accurateOppositionHalfPasses': 51, 'totalOppositionHalfPasses': 54, 'aerialLost': 3, 'aerialWon': 4, 'duelLost': 6, 'duelWon': 5, 'dispossessed': 1, 'totalClearance': 4, 'interceptionWon': 1, 'ballRecovery': 2, 'totalTackle': 1, 'wonTackle': 1, 'unsuccessfulTouch': 1, 'fouls': 2, 'minutesPlayed': 90, 'touches': 87, 'rating': 7.2, 'possessionLostCtrl': 5, 'expectedAssists': 0.0696148, 'ratingVersions': {'original': 7.2, 'alternative': 7.2}, 'totalShots': 0}}, {'player': {'name': 'İlkay Gündoğan', 'slug': 'ilkay-gundogan', 'shortName': 'İ. Gündoğan', 'position': 'M', 'jerseyNumber': '20', 'height': 180, 'userCount': 64304, 'gender': 'M', 'sofascoreId': 'IGunny', 'id': 45853, 'country': {'alpha2': 'DE', 'alpha3': 'DEU', 'name': 'Germany', 'slug': 'germany'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 656726400, 'proposedMarketValueRaw': {'value': 3800000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'إلكاي غوندوغان', 'hi': 'इल्के गुंडोगन', 'bn': 'ইল্কে গুন্ডোগান'}, 'shortNameTranslation': {'ar': 'إ. غوندوغان', 'hi': 'आई. गुंडोगन', 'bn': 'আই. গুন্ডোগান'}}}, 'teamId': 3061, 'shirtNumber': 19, 'jerseyNumber': '19', 'position': 'M', 'substitute': False, 'statistics': {'totalPass': 96, 'accuratePass': 87, 'totalLongBalls': 5, 'accurateLongBalls': 4, 'goalAssist': 0, 'accurateOwnHalfPasses': 18, 'totalOwnHalfPasses': 20, 'accurateOppositionHalfPasses': 71, 'totalOppositionHalfPasses': 82, 'totalCross': 6, 'accurateCross': 2, 'aerialWon': 1, 'duelLost': 3, 'duelWon': 5, 'challengeLost': 1, 'totalContest': 1, 'blockedScoringAttempt': 1, 'totalClearance': 1, 'ballRecovery': 8, 'totalTackle': 3, 'wonTackle': 1, 'wasFouled': 1, 'fouls': 1, 'minutesPlayed': 89, 'touches': 112, 'rating': 7.6, 'possessionLostCtrl': 14, 'expectedGoals': 0.0955, 'expectedAssists': 0.40534, 'keyPass': 2, 'ratingVersions': {'original': 7.6, 'alternative': 8.2}, 'totalShots': 1}}, {'player': {'name': 'Savinho', 'slug': 'savio', 'shortName': 'Savinho', 'position': 'M', 'jerseyNumber': '26', 'height': 176, 'userCount': 58099, 'gender': 'M', 'sofascoreId': 'Savinho', 'id': 1046795, 'country': {'alpha2': 'BR', 'alpha3': 'BRA', 'name': 'Brazil', 'slug': 'brazil'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 1081555200, 'proposedMarketValueRaw': {'value': 52000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'سافيو', 'hi': 'सैवियो', 'bn': 'স্যাভিও'}, 'shortNameTranslation': {'ar': 'سافيو', 'hi': 'सैवियो', 'bn': 'স্যাভিও'}}}, 'teamId': 17, 'shirtNumber': 26, 'jerseyNumber': '26', 'position': 'M', 'substitute': False, 'statistics': {'totalPass': 41, 'accuratePass': 38, 'goalAssist': 1, 'accurateOwnHalfPasses': 4, 'totalOwnHalfPasses': 4, 'accurateOppositionHalfPasses': 34, 'totalOppositionHalfPasses': 39, 'totalCross': 2, 'duelLost': 5, 'duelWon': 6, 'dispossessed': 2, 'totalContest': 4, 'wonContest': 2, 'bigChanceCreated': 1, 'onTargetScoringAttempt': 1, 'blockedScoringAttempt': 1, 'interceptionWon': 1, 'ballRecovery': 3, 'totalTackle': 2, 'wonTackle': 2, 'unsuccessfulTouch': 3, 'wasFouled': 2, 'fouls': 1, 'totalOffside': 1, 'minutesPlayed': 85, 'touches': 61, 'rating': 8.4, 'possessionLostCtrl': 12, 'expectedGoals': 0.1583, 'expectedGoalsOnTarget': 0.5484, 'expectedAssists': 0.476458, 'keyPass': 5, 'ratingVersions': {'original': 8.4, 'alternative': 7.9}, 'totalShots': 2}}, {'player': {'name': 'Jack Grealish', 'slug': 'jack-grealish', 'shortName': 'J. Grealish', 'position': 'M', 'jerseyNumber': '18', 'height': 180, 'userCount': 68671, 'gender': 'M', 'sofascoreId': 'JGrealish', 'id': 189061, 'country': {'alpha2': 'EN', 'alpha3': 'ENG', 'name': 'England', 'slug': 'england'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 810691200, 'proposedMarketValueRaw': {'value': 29000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'جاك غريليش', 'hi': 'जैक ग्रेलिश', 'bn': 'জ্যাক গ্রেলিশ'}, 'shortNameTranslation': {'ar': 'ج. غريليش', 'hi': 'जे. ग्रेलिश', 'bn': 'জে গ্রেলিশ'}}}, 'teamId': 48, 'shirtNumber': 10, 'jerseyNumber': '10', 'position': 'M', 'substitute': False, 'statistics': {'totalPass': 55, 'accuratePass': 51, 'totalLongBalls': 1, 'accurateLongBalls': 1, 'goalAssist': 0, 'accurateOwnHalfPasses': 10, 'totalOwnHalfPasses': 10, 'accurateOppositionHalfPasses': 41, 'totalOppositionHalfPasses': 45, 'aerialLost': 1, 'duelLost': 8, 'duelWon': 1, 'challengeLost': 1, 'dispossessed': 3, 'totalContest': 1, 'shotOffTarget': 1, 'onTargetScoringAttempt': 1, 'goals': 1, 'totalClearance': 1, 'ballRecovery': 5, 'unsuccessfulTouch': 1, 'wasFouled': 1, 'fouls': 2, 'minutesPlayed': 90, 'touches': 68, 'rating': 7.8, 'possessionLostCtrl': 9, 'expectedGoals': 0.3456, 'expectedGoalsOnTarget': 0.9557, 'expectedAssists': 0.153884, 'keyPass': 2, 'ratingVersions': {'original': 7.8, 'alternative': 8.1}, 'totalShots': 2}}, {'player': {'name': 'Jérémy Doku', 'slug': 'jeremy-doku', 'shortName': 'J. Doku', 'position': 'M', 'jerseyNumber': '11', 'height': 173, 'userCount': 65251, 'gender': 'M', 'sofascoreId': 'Dokss', 'id': 934386, 'country': {'alpha2': 'BE', 'alpha3': 'BEL', 'name': 'Belgium', 'slug': 'belgium'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 1022457600, 'proposedMarketValueRaw': {'value': 51000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'جيريمي دوكو', 'hi': 'जेरेमी डोकू', 'bn': 'জেরেমি ডকু'}, 'shortNameTranslation': {'ar': 'ج. دوكو', 'hi': 'जे. डोकू', 'bn': 'জে. ডকু'}}}, 'teamId': 17, 'shirtNumber': 11, 'jerseyNumber': '11', 'position': 'M', 'substitute': False, 'statistics': {'totalPass': 50, 'accuratePass': 45, 'totalLongBalls': 1, 'accurateLongBalls': 1, 'goalAssist': 0, 'accurateOwnHalfPasses': 5, 'totalOwnHalfPasses': 5, 'accurateOppositionHalfPasses': 41, 'totalOppositionHalfPasses': 49, 'totalCross': 4, 'accurateCross': 1, 'duelLost': 7, 'duelWon': 5, 'dispossessed': 3, 'totalContest': 7, 'wonContest': 3, 'ballRecovery': 2, 'totalTackle': 1, 'wonTackle': 1, 'unsuccessfulTouch': 5, 'wasFouled': 1, 'minutesPlayed': 78, 'touches': 72, 'rating': 7.1, 'possessionLostCtrl': 20, 'expectedAssists': 0.591452, 'keyPass': 2, 'ratingVersions': {'original': 7.1, 'alternative': 7.5}, 'totalShots': 0}}, {'player': {'name': 'Omar Marmoush', 'slug': 'omar-marmoush', 'shortName': 'O. Marmoush', 'position': 'F', 'jerseyNumber': '7', 'height': 183, 'userCount': 179920, 'gender': 'M', 'sofascoreId': 'OMarmoush', 'id': 873554, 'country': {'alpha2': 'EG', 'alpha3': 'EGY', 'name': 'Egypt', 'slug': 'egypt'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 918345600, 'proposedMarketValueRaw': {'value': 82000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'عمر مرموش', 'hi': 'उमर मार्मौश', 'bn': 'ওমর মারমাউস'}, 'shortNameTranslation': {'ar': 'ع. مرموش', 'hi': 'ओ. मार्मौश', 'bn': 'ও. মারমাউস'}}}, 'teamId': 17, 'shirtNumber': 7, 'jerseyNumber': '7', 'position': 'F', 'substitute': False, 'statistics': {'totalPass': 19, 'accuratePass': 17, 'goalAssist': 0, 'accurateOwnHalfPasses': 3, 'totalOwnHalfPasses': 3, 'accurateOppositionHalfPasses': 14, 'totalOppositionHalfPasses': 16, 'aerialWon': 1, 'duelLost': 2, 'duelWon': 4, 'totalContest': 1, 'wonContest': 1, 'shotOffTarget': 2, 'onTargetScoringAttempt': 3, 'blockedScoringAttempt': 4, 'goals': 1, 'ballRecovery': 1, 'unsuccessfulTouch': 5, 'wasFouled': 2, 'fouls': 2, 'totalOffside': 1, 'minutesPlayed': 90, 'touches': 39, 'rating': 8.1, 'possessionLostCtrl': 8, 'expectedGoals': 1.4524, 'expectedGoalsOnTarget': 1.2129, 'expectedAssists': 0.0436257, 'ratingVersions': {'original': 8.1, 'alternative': 6.9}, 'totalShots': 9}}, {'player': {'name': 'James McAtee', 'slug': 'james-mcatee', 'shortName': 'J. McAtee', 'position': 'M', 'jerseyNumber': '24', 'height': 180, 'userCount': 11550, 'gender': 'M', 'sofascoreId': 'jamesmcatee_', 'id': 1003334, 'country': {'alpha2': 'EN', 'alpha3': 'ENG', 'name': 'England', 'slug': 'england'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 1034899200, 'proposedMarketValueRaw': {'value': 23000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'جيمس مكاتي', 'hi': 'जेम्स मैकएटी', 'bn': 'জেমস ম্যাকাটি'}, 'shortNameTranslation': {'ar': 'ج. مكاتي', 'hi': 'जे. मैकएटी', 'bn': 'জে. ম্যাকাটি'}}}, 'teamId': 14, 'shirtNumber': 87, 'jerseyNumber': '87', 'position': 'M', 'substitute': True, 'statistics': {'totalPass': 6, 'accuratePass': 5, 'goalAssist': 0, 'accurateOwnHalfPasses': 2, 'totalOwnHalfPasses': 3, 'accurateOppositionHalfPasses': 3, 'totalOppositionHalfPasses': 3, 'duelLost': 1, 'challengeLost': 1, 'shotOffTarget': 2, 'unsuccessfulTouch': 1, 'minutesPlayed': 12, 'touches': 9, 'rating': 6.7, 'possessionLostCtrl': 2, 'expectedGoals': 0.0269, 'expectedAssists': 0.0138835, 'ratingVersions': {'original': 6.7, 'alternative': 6.6}, 'totalShots': 2}}, {'player': {'name': 'Oscar Bobb', 'firstName': 'Oscar Bobb', 'lastName': '', 'slug': 'oscar-bobb', 'shortName': 'O. Bobb', 'position': 'M', 'jerseyNumber': '52', 'height': 174, 'userCount': 17117, 'gender': 'M', 'sofascoreId': 'oscarbobb', 'id': 1065216, 'country': {'alpha2': 'NO', 'alpha3': 'NOR', 'name': 'Norway', 'slug': 'norway'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 1057968000, 'proposedMarketValueRaw': {'value': 29000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'أوسكار بوب', 'hi': 'ऑस्कर बॉब', 'bn': 'অস্কার বব'}, 'shortNameTranslation': {'ar': 'أ. بوب', 'hi': 'ओ. बॉब', 'bn': 'ও. বব'}}}, 'teamId': 17, 'shirtNumber': 52, 'jerseyNumber': '52', 'position': 'M', 'substitute': True, 'statistics': {'totalPass': 2, 'accuratePass': 2, 'goalAssist': 0, 'accurateOwnHalfPasses': 2, 'totalOwnHalfPasses': 2, 'ballRecovery': 1, 'minutesPlayed': 9, 'touches': 2, 'rating': 6.5, 'expectedAssists': 7.27e-06, 'ratingVersions': {'original': 6.5, 'alternative': 6.6}, 'totalShots': 0}}, {'player': {'name': 'Vitor Reis', 'slug': 'reis-vitor', 'shortName': 'V. Reis', 'position': 'D', 'jerseyNumber': '12', 'height': 186, 'userCount': 12746, 'gender': 'M', 'sofascoreId': 'vitorreiss_06', 'id': 1485300, 'country': {'alpha2': 'BR', 'alpha3': 'BRA', 'name': 'Brazil', 'slug': 'brazil'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 1137024000, 'proposedMarketValueRaw': {'value': 31000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'فيتور ريس', 'hi': 'विटोर रीस', 'bn': 'ভিটর রেইস'}, 'shortNameTranslation': {'ar': 'ف. ريس', 'hi': 'वी. रीस', 'bn': 'ভি. রেইস'}}}, 'teamId': 24264, 'shirtNumber': 22, 'jerseyNumber': '22', 'position': 'D', 'substitute': True, 'statistics': {'totalPass': 2, 'accuratePass': 2, 'goalAssist': 0, 'accurateOwnHalfPasses': 2, 'totalOwnHalfPasses': 2, 'duelWon': 1, 'totalContest': 1, 'wonContest': 1, 'totalClearance': 1, 'minutesPlayed': 1, 'touches': 4, 'expectedAssists': 3.82e-06, 'totalShots': 0}}, {'player': {'name': 'Rico Lewis', 'firstName': 'Rico Lewis', 'lastName': '', 'slug': 'rico-lewis', 'shortName': 'R. Lewis', 'position': 'D', 'jerseyNumber': '82', 'height': 170, 'userCount': 17898, 'gender': 'M', 'sofascoreId': 'Rico_Lewis', 'id': 1136731, 'country': {'alpha2': 'EN', 'alpha3': 'ENG', 'name': 'England', 'slug': 'england'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 1100995200, 'proposedMarketValueRaw': {'value': 37000000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ريكو لويس', 'hi': 'रिको लुईस', 'bn': 'রিকো লুইস'}, 'shortNameTranslation': {'ar': 'ر. لويس', 'hi': 'आर. लुईस', 'bn': 'আর. লুইস'}}}, 'teamId': 17, 'shirtNumber': 82, 'jerseyNumber': '82', 'position': 'D', 'substitute': True, 'statistics': {'totalPass': 2, 'accuratePass': 1, 'totalLongBalls': 1, 'goalAssist': 0, 'totalOwnHalfPasses': 1, 'accurateOppositionHalfPasses': 1, 'totalOppositionHalfPasses': 1, 'minutesPlayed': 1, 'touches': 2, 'possessionLostCtrl': 1, 'expectedAssists': 0.00137256, 'totalShots': 0}}, {'player': {'name': 'Stefan Ortega', 'slug': 'stefan-ortega', 'shortName': 'S. Ortega', 'position': 'G', 'jerseyNumber': '18', 'height': 186, 'userCount': 10851, 'gender': 'M', 'sofascoreId': 'stefan.ortega1', 'id': 125274, 'country': {'alpha2': 'DE', 'alpha3': 'DEU', 'name': 'Germany', 'slug': 'germany'}, 'marketValueCurrency': 'EUR', 'dateOfBirthTimestamp': 721008000, 'proposedMarketValueRaw': {'value': 5800000, 'currency': 'EUR'}, 'fieldTranslations': {'nameTranslation': {'ar': 'ستيفان أورتيغا', 'hi': 'स्टीफन ऑर्टेगा', 'bn': 'স্টেফান ওর্তেগা'}, 'shortNameTranslation': {'ar': 'س. أورتيغا', 'hi': 'एस. ऑर्टेगा', 'bn': 'এস. ওর্

In [82]:
df8 = pd.DataFrame(data4)
df8

,confirmed,home,away
players,True,"[{'player': {'name': 'Ederson', 'slug': 'eders...","[{'player': {'name': 'Mads Hermansen', 'slug':..."
supportStaff,True,[],[]
formation,True,4-2-3-1,3-4-2-1
playerColor,True,"{'primary': 'abd1f5', 'number': 'ffffff', 'out...","{'primary': '2424eb', 'number': 'ffffff', 'out..."
goalkeeperColor,True,"{'primary': 'ee4665', 'number': '070707', 'out...","{'primary': '5ee937', 'number': 'ffffff', 'out..."
missingPlayers,True,"[{'player': {'name': 'Manuel Akanji', 'slug': ...","[{'player': {'name': 'Abdul Fatawu Issahaku', ..."

In [84]:
print(type(data4))

<class 'dict'>

In [85]:
print(data4.keys())

dict_keys(['confirmed', 'home', 'away'])

In [86]:
home_players = pd.json_normalize(data4['home']['players'])
home_players

,teamId,shirtNumber,jerseyNumber,position,substitute,player.name,player.slug,player.shortName,player.position,player.jerseyNumber,...,statistics.interceptionWon,statistics.wasFouled,statistics.totalCross,statistics.accurateCross,statistics.bigChanceCreated,statistics.onTargetScoringAttempt,statistics.totalOffside,statistics.expectedGoalsOnTarget,statistics.shotOffTarget,statistics.goals
0,3052,31,31,G,False,Ederson,ederson,Ederson,G,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17,27,27,D,False,Matheus Nunes,matheus-nunes,M. Nunes,D,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17,3,3,D,False,Rúben Dias,ruben-dias,R. Dias,D,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17,24,24,D,False,Joško Gvardiol,josko-gvardiol,J. Gvardiol,D,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17,75,75,D,False,Nico O'Reilly,nico-o-reilly,N. O’Reilly,D,33,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,17,14,14,M,False,Nico González,nico-gonzalez,N. González,M,14,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3061,19,19,M,False,İlkay Gündoğan,ilkay-gundogan,İ. Gündoğan,M,20,...,NaN,1.0,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
7,17,26,26,M,False,Savinho,savio,Savinho,M,26,...,1.0,2.0,2.0,NaN,1.0,1.0,1.0,0.5484,NaN,NaN
8,48,10,10,M,False,Jack Grealish,jack-grealish,J. Grealish,M,18,...,NaN,1.0,NaN,NaN,NaN,1.0,NaN,0.9557,1.0,1.0
9,17,11,11,M,False,Jérémy Doku,jeremy-doku,J. Doku,M,11,...,NaN,1.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
10,17,7,7,F,False,Omar Marmoush,omar-marmoush,O. Marmoush,F,7,...,NaN,2.0,NaN,NaN,NaN,3.0,1.0,1.2129,2.0,1.0
11,14,87,87,M,True,James McAtee,james-mcatee,J. McAtee,M,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
12,17,52,52,M,True,Oscar Bobb,oscar-bobb,O. Bobb,M,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,24264,22,22,D,True,Vitor Reis,reis-vitor,V. Reis,D,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,17,82,82,D,True,Rico Lewis,rico-lewis,R. Lewis,D,82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,17,18,18,G,True,Stefan Ortega,stefan-ortega,S. Ortega,G,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,8,8,M,True,Mateo Kovačić,mateo-kovacic,M. Kovačić,M,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2714,17,17,M,True,Kevin De Bruyne,kevin-de-bruyne,K. De Bruyne,M,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,17,20,20,M,True,Bernardo Silva,bernardo-silva,B. Silva,M,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,17,47,47,M,True,Phil Foden,phil-foden,P. Foden,M,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [177]:
away_players = pd.json_normalize(data4['away']['players'])
away_players

,teamId,shirtNumber,jerseyNumber,position,substitute,player.name,player.slug,player.shortName,player.position,player.jerseyNumber,...,statistics.wonTackle,statistics.fouls,statistics.keyPass,statistics.dispossessed,statistics.wonContest,player.sofascoreId,statistics.shotOffTarget,statistics.expectedGoals,captain,statistics.totalOffside
0,37,30,30,G,False,Mads Hermansen,mads-hermansen,M. Hermansen,G,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,31,3,3,D,False,Wout Faes,wout-faes,W. Faes,D,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,64,4,4,D,False,Conor Coady,conor-coady,C. Coady,D,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,31,33,33,D,False,Luke Thomas,luke-thomas,L. Thomas,D,33,...,3.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,34,2,2,M,False,James Justin,james-justin,J. Justin,D,24,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3050,6,6,M,False,Wilfred Ndidi,wilfred-ndidi,W. Ndidi,M,4,...,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
6,31,24,24,M,False,Boubakary Soumaré,boubakary-soumare,B. Soumaré,M,24,...,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
7,31,16,16,M,False,Victor Kristiansen,kristiansen-victor,V. Kristiansen,D,16,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,31,20,20,F,False,Patson Daka,patson-daka,P. Daka,F,20,...,NaN,1.0,NaN,NaN,NaN,patsondaka,NaN,NaN,NaN,NaN
9,2677,11,11,F,False,Bilal El Khannouss,bilal-el-khannouss,B. E. Khannouss,M,11,...,1.0,NaN,NaN,1.0,NaN,bilalekns_34,1.0,0.0192,NaN,NaN
10,2761,9,9,F,False,Jamie Vardy,jamie-vardy,J. Vardy,F,10,...,NaN,1.0,NaN,1.0,NaN,Vardy7,NaN,NaN,True,NaN
11,31,22,22,M,True,Oliver Skipp,skipp-oliver,O. Skipp,M,22,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,31,5,5,D,True,Caleb Okoli,caleb-okoli,C. Okoli,D,5,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,38,40,40,M,True,Facundo Buonanotte,facundo-buonanotte,F. Buonanotte,M,40,...,1.0,1.0,NaN,NaN,NaN,facubuonanotte_,NaN,NaN,NaN,NaN
14,31,21,21,D,True,Ricardo Pereira,ricardo-pereira,R. Pereira,D,21,...,NaN,1.0,NaN,NaN,2.0,NaN,1.0,0.0537,NaN,NaN
15,31,18,18,F,True,Jordan Ayew,jordan-ayew,J. Ayew,F,9,...,NaN,NaN,NaN,NaN,1.0,jordanayew9,NaN,NaN,NaN,1.0
16,31,41,41,G,True,Jakub Stolarczyk,jakub-stolarczyk,J. Stolarczyk,G,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2793,25,25,D,True,Woyo Coulibaly,woyo-coulibaly,W. Coulibaly,D,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,31,14,14,F,True,Bobby Decordova-Reid,bobby-decordova-reid,B. Reid,M,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,31,10,10,F,True,Stephy Mavididi,stephy-mavididi,S. Mavididi,M,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [178]:
match_info = {
    "home_formation": data4['home'].get('formation'),
    "away_formation": data4['away'].get('formation'),
    "confirmed": data4['confirmed']
}
print(match_info)

{'home_formation': '4-2-3-1', 'away_formation': '3-4-2-1', 'confirmed': True}

In [179]:
home_players['side'] = 'home'
home_players['formation'] = data4['home'].get('formation')
home_players

,teamId,shirtNumber,jerseyNumber,position,substitute,player.name,player.slug,player.shortName,player.position,player.jerseyNumber,...,statistics.totalCross,statistics.accurateCross,statistics.bigChanceCreated,statistics.onTargetScoringAttempt,statistics.totalOffside,statistics.expectedGoalsOnTarget,statistics.shotOffTarget,statistics.goals,side,formation
0,3052,31,31,G,False,Ederson,ederson,Ederson,G,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
1,17,27,27,D,False,Matheus Nunes,matheus-nunes,M. Nunes,D,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
2,17,3,3,D,False,Rúben Dias,ruben-dias,R. Dias,D,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
3,17,24,24,D,False,Joško Gvardiol,josko-gvardiol,J. Gvardiol,D,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
4,17,75,75,D,False,Nico O'Reilly,nico-o-reilly,N. O’Reilly,D,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
5,17,14,14,M,False,Nico González,nico-gonzalez,N. González,M,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
6,3061,19,19,M,False,İlkay Gündoğan,ilkay-gundogan,İ. Gündoğan,M,20,...,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
7,17,26,26,M,False,Savinho,savio,Savinho,M,26,...,2.0,NaN,1.0,1.0,1.0,0.5484,NaN,NaN,home,4-2-3-1
8,48,10,10,M,False,Jack Grealish,jack-grealish,J. Grealish,M,18,...,NaN,NaN,NaN,1.0,NaN,0.9557,1.0,1.0,home,4-2-3-1
9,17,11,11,M,False,Jérémy Doku,jeremy-doku,J. Doku,M,11,...,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
10,17,7,7,F,False,Omar Marmoush,omar-marmoush,O. Marmoush,F,7,...,NaN,NaN,NaN,3.0,1.0,1.2129,2.0,1.0,home,4-2-3-1
11,14,87,87,M,True,James McAtee,james-mcatee,J. McAtee,M,24,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,home,4-2-3-1
12,17,52,52,M,True,Oscar Bobb,oscar-bobb,O. Bobb,M,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
13,24264,22,22,D,True,Vitor Reis,reis-vitor,V. Reis,D,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
14,17,82,82,D,True,Rico Lewis,rico-lewis,R. Lewis,D,82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
15,17,18,18,G,True,Stefan Ortega,stefan-ortega,S. Ortega,G,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
16,17,8,8,M,True,Mateo Kovačić,mateo-kovacic,M. Kovačić,M,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
17,2714,17,17,M,True,Kevin De Bruyne,kevin-de-bruyne,K. De Bruyne,M,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
18,17,20,20,M,True,Bernardo Silva,bernardo-silva,B. Silva,M,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
19,17,47,47,M,True,Phil Foden,phil-foden,P. Foden,M,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1

In [180]:
away_players['side'] = 'away'
away_players['formation'] = data4['away'].get('formation')
away_players

,teamId,shirtNumber,jerseyNumber,position,substitute,player.name,player.slug,player.shortName,player.position,player.jerseyNumber,...,statistics.keyPass,statistics.dispossessed,statistics.wonContest,player.sofascoreId,statistics.shotOffTarget,statistics.expectedGoals,captain,statistics.totalOffside,side,formation
0,37,30,30,G,False,Mads Hermansen,mads-hermansen,M. Hermansen,G,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
1,31,3,3,D,False,Wout Faes,wout-faes,W. Faes,D,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
2,64,4,4,D,False,Conor Coady,conor-coady,C. Coady,D,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
3,31,33,33,D,False,Luke Thomas,luke-thomas,L. Thomas,D,33,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
4,34,2,2,M,False,James Justin,james-justin,J. Justin,D,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
5,3050,6,6,M,False,Wilfred Ndidi,wilfred-ndidi,W. Ndidi,M,4,...,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
6,31,24,24,M,False,Boubakary Soumaré,boubakary-soumare,B. Soumaré,M,24,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
7,31,16,16,M,False,Victor Kristiansen,kristiansen-victor,V. Kristiansen,D,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
8,31,20,20,F,False,Patson Daka,patson-daka,P. Daka,F,20,...,NaN,NaN,NaN,patsondaka,NaN,NaN,NaN,NaN,away,3-4-2-1
9,2677,11,11,F,False,Bilal El Khannouss,bilal-el-khannouss,B. E. Khannouss,M,11,...,NaN,1.0,NaN,bilalekns_34,1.0,0.0192,NaN,NaN,away,3-4-2-1
10,2761,9,9,F,False,Jamie Vardy,jamie-vardy,J. Vardy,F,10,...,NaN,1.0,NaN,Vardy7,NaN,NaN,True,NaN,away,3-4-2-1
11,31,22,22,M,True,Oliver Skipp,skipp-oliver,O. Skipp,M,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
12,31,5,5,D,True,Caleb Okoli,caleb-okoli,C. Okoli,D,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
13,38,40,40,M,True,Facundo Buonanotte,facundo-buonanotte,F. Buonanotte,M,40,...,NaN,NaN,NaN,facubuonanotte_,NaN,NaN,NaN,NaN,away,3-4-2-1
14,31,21,21,D,True,Ricardo Pereira,ricardo-pereira,R. Pereira,D,21,...,NaN,NaN,2.0,NaN,1.0,0.0537,NaN,NaN,away,3-4-2-1
15,31,18,18,F,True,Jordan Ayew,jordan-ayew,J. Ayew,F,9,...,NaN,NaN,1.0,jordanayew9,NaN,NaN,NaN,1.0,away,3-4-2-1
16,31,41,41,G,True,Jakub Stolarczyk,jakub-stolarczyk,J. Stolarczyk,G,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
17,2793,25,25,D,True,Woyo Coulibaly,woyo-coulibaly,W. Coulibaly,D,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
18,31,14,14,F,True,Bobby Decordova-Reid,bobby-decordova-reid,B. Reid,M,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
19,31,10,10,F,True,Stephy Mavididi,stephy-mavididi,S. Mavididi,M,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1

In [91]:
all_players = pd.concat([home_players, away_players], ignore_index=True)
all_players

,teamId,shirtNumber,jerseyNumber,position,substitute,player.name,player.slug,player.shortName,player.position,player.jerseyNumber,...,statistics.totalCross,statistics.accurateCross,statistics.bigChanceCreated,statistics.onTargetScoringAttempt,statistics.totalOffside,statistics.expectedGoalsOnTarget,statistics.shotOffTarget,statistics.goals,side,formation
0,3052,31.0,31,G,False,Ederson,ederson,Ederson,G,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
1,17,27.0,27,D,False,Matheus Nunes,matheus-nunes,M. Nunes,D,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
2,17,3.0,3,D,False,Rúben Dias,ruben-dias,R. Dias,D,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
3,17,24.0,24,D,False,Joško Gvardiol,josko-gvardiol,J. Gvardiol,D,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
4,17,75.0,75,D,False,Nico O'Reilly,nico-o-reilly,N. O’Reilly,D,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
5,17,14.0,14,M,False,Nico González,nico-gonzalez,N. González,M,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
6,3061,19.0,19,M,False,İlkay Gündoğan,ilkay-gundogan,İ. Gündoğan,M,20,...,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
7,17,26.0,26,M,False,Savinho,savio,Savinho,M,26,...,2.0,NaN,1.0,1.0,1.0,0.5484,NaN,NaN,home,4-2-3-1
8,48,10.0,10,M,False,Jack Grealish,jack-grealish,J. Grealish,M,18,...,NaN,NaN,NaN,1.0,NaN,0.9557,1.0,1.0,home,4-2-3-1
9,17,11.0,11,M,False,Jérémy Doku,jeremy-doku,J. Doku,M,11,...,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
10,17,7.0,7,F,False,Omar Marmoush,omar-marmoush,O. Marmoush,F,7,...,NaN,NaN,NaN,3.0,1.0,1.2129,2.0,1.0,home,4-2-3-1
11,14,87.0,87,M,True,James McAtee,james-mcatee,J. McAtee,M,24,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,home,4-2-3-1
12,17,52.0,52,M,True,Oscar Bobb,oscar-bobb,O. Bobb,M,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
13,24264,22.0,22,D,True,Vitor Reis,reis-vitor,V. Reis,D,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
14,17,82.0,82,D,True,Rico Lewis,rico-lewis,R. Lewis,D,82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
15,17,18.0,18,G,True,Stefan Ortega,stefan-ortega,S. Ortega,G,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
16,17,8.0,8,M,True,Mateo Kovačić,mateo-kovacic,M. Kovačić,M,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
17,2714,17.0,17,M,True,Kevin De Bruyne,kevin-de-bruyne,K. De Bruyne,M,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
18,17,20.0,20,M,True,Bernardo Silva,bernardo-silva,B. Silva,M,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
19,17,47.0,47,M,True,Phil Foden,phil-foden,P. Foden,M,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,4-2-3-1
20,241802,99.0,99,G,False,Vítor Baía,vitor-baia,V. Baía,G,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
21,241802,12.0,12,D,False,Sergi Barjuán,sergi-barjuan,S. Barjuán,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
22,241802,5.0,5,D,False,Carles Puyol,carles-puyol,C. Puyol,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
23,241802,19.0,19,D,False,Fernando Navarro,fernando-navarro,F. Navarro,D,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
24,241802,3.0,3,D,False,Frank de Boer,frank-de-boer,F. d. Boer,D,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
25,241802,15.0,15,M,False,Edmílson,edmilson,Edmílson,M,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
26,241802,6.0,6,M,False,Xavi,xavi,X. Hernández,M,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
27,241802,17.0,17,M,False,Gaizka Mendieta,gaizka-mendieta,G. Mendieta,M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
28,241802,8.0,8,F,False,Ludovic Giuly,ludovic-giuly,L. Giuly,F,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
29,241802,9.0,9,F,False,Patrick Kluivert,patrick-kluivert,P. Kluivert,F,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
30,241802,10.0,10,M,False,Rivaldo,rivaldo,Rivaldo,M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
31,477899,NaN,NaN,G,True,Jesús Angoy,jesus-angoy,J. Angoy,G,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
32,241802,NaN,NaN,D,True,Samuel Okunowo,samuel-okunowo,S. Okunowo,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
33,241802,NaN,NaN,D,True,Marc Valiente,marc-valiente,M. Valiente,D,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
34,241802,NaN,NaN,M,True,Phillip Cocu,phillip-cocu,P. Cocu,M,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
35,241802,NaN,NaN,M,True,Jofre,jofre,Jofre,M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
36,2818,NaN,NaN,M,True,Roberto Trashorras,roberto-trashorras,R. Trashorras,M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
37,241802,NaN,NaN,M,True,Giovanni,giovanni,Giovanni,M,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
38,241802,NaN,NaN,F,True,Javier Saviola,javier-saviola,J. Saviola,F,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1
39,3009,NaN,NaN,F,True,Ricardo Quaresma,ricardo-quaresma,R. Quaresma,F,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,away,3-4-2-1

In [181]:
all_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 81 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   teamId                                            40 non-null     int64
 1   shirtNumber                                       31 non-null     float64
 2   jerseyNumber                                      31 non-null     object
 3   position                                          40 non-null     object
 4   substitute                                        40 non-null     bool
 5   player.name                                       40 non-null     object
 6   player.slug                                       40 non-null     object
 7   player.shortName                                  40 non-null     object
 8   player.position                                   40 non-null     object
 9   player.jerseyNumber                               28 non-null     object
 10  player.height                                     40 non-null     int64
 11  player.userCount                                  40 non-null     int64
 12  player.gender                                     25 non-null     object
 13  player.sofascoreId                                20 non-null     object
 14  player.id                                         40 non-null     int64
 15  player.country.alpha2                             40 non-null     object
 16  player.country.alpha3                             40 non-null     object
 17  player.country.name                               40 non-null     object
 18  player.country.slug                               40 non-null     object
 19  player.marketValueCurrency                        40 non-null     object
 20  player.dateOfBirthTimestamp                       40 non-null     int64
 21  player.proposedMarketValueRaw.value               20 non-null     float64
 22  player.proposedMarketValueRaw.currency            20 non-null     object
 23  player.fieldTranslations.nameTranslation.ar       40 non-null     object
 24  player.fieldTranslations.nameTranslation.hi       23 non-null     object
 25  player.fieldTranslations.nameTranslation.bn       23 non-null     object
 26  player.fieldTranslations.shortNameTranslation.ar  40 non-null     object
 27  player.fieldTranslations.shortNameTranslation.hi  23 non-null     object
 28  player.fieldTranslations.shortNameTranslation.bn  23 non-null     object
 29  statistics.totalPass                              15 non-null     float64
 30  statistics.accuratePass                           15 non-null     float64
 31  statistics.totalLongBalls                         10 non-null     float64
 32  statistics.accurateLongBalls                      8 non-null      float64
 33  statistics.goalAssist                             15 non-null     float64
 34  statistics.accurateOwnHalfPasses                  14 non-null     float64
 35  statistics.totalOwnHalfPasses                     15 non-null     float64
 36  statistics.totalClearance                         8 non-null      float64
 37  statistics.ballRecovery                           12 non-null     float64
 38  statistics.totalKeeperSweeper                     1 non-null      float64
 39  statistics.accurateKeeperSweeper                  1 non-null      float64
 40  statistics.minutesPlayed                          15 non-null     float64
 41  statistics.touches                                15 non-null     float64
 42  statistics.rating                                 13 non-null     float64
 43  statistics.expectedAssists                        15 non-null     float64
 44  statistics.ratingVersions.original                13 non-null     float64
 45  statistics.ratingVersions.alternative             13 non-null     float64
 46  statistics.totalShots                             20 non-null     float64
 47  player.firstName                                  13 non-null     object
 48  player.lastName                                   13 non-null     object
 49  statistics.accurateOppositionHalfPasses           12 non-null     float64
 50  statistics.totalOppositionHalfPasses              12 non-null     float64
 51  statistics.aerialLost                             5 non-null      float64
 52  statistics.duelLost                               10 non-null     float64
 53  statistics.duelWon                                11 non-null     float64
 54  statistics.totalContest                           8 non-null      float64
 55  statistics.wonContest                             6 non-null      float64
 56  statistics.unsuccessfulTouch                      10 non-null     float64
 57  statistics.fouls                                  7 non-null      float64
 58  statistics.possessionLostCtrl                     12 non-null     float64
 59  captain                                           2 non-null      object
 60  statistics.aerialWon                              5 non-null      float64
 61  statistics.dispossessed                           5 non-null      float64
 62  statistics.blockedScoringAttempt                  5 non-null      float64
 63  statistics.lastManTackle                          1 non-null      float64
 64  statistics.totalTackle                            6 non-null      float64
 65  statistics.wonTackle                              5 non-null      float64
 66  statistics.expectedGoals                          7 non-null      float64
 67  statistics.keyPass                                6 non-null      float64
 68  statistics.challengeLost                          4 non-null      float64
 69  statistics.interceptionWon                        3 non-null      float64
 70  statistics.wasFouled                              6 non-null      float64
 71  statistics.totalCross                             3 non-null      float64
 72  statistics.accurateCross                          2 non-null      float64
 73  statistics.bigChanceCreated                       1 non-null      float64
 74  statistics.onTargetScoringAttempt                 3 non-null      float64
 75  statistics.totalOffside                           2 non-null      float64
 76  statistics.expectedGoalsOnTarget                  3 non-null      float64
 77  statistics.shotOffTarget                          3 non-null      float64
 78  statistics.goals                                  2 non-null      float64
 79  side                                              40 non-null     object
 80  formation                                         40 non-null     object
dtypes: bool(1), float64(49), int64(5), object(26)
memory usage: 25.2+ KB

In [182]:
home_players.columns

Index(['teamId', 'shirtNumber', 'jerseyNumber', 'position', 'substitute',
       'player.name', 'player.slug', 'player.shortName', 'player.position',
       'player.jerseyNumber', 'player.height', 'player.userCount',
       'player.gender', 'player.sofascoreId', 'player.id',
       'player.country.alpha2', 'player.country.alpha3', 'player.country.name',
       'player.country.slug', 'player.marketValueCurrency',
       'player.dateOfBirthTimestamp', 'player.proposedMarketValueRaw.value',
       'player.proposedMarketValueRaw.currency',
       'player.fieldTranslations.nameTranslation.ar',
       'player.fieldTranslations.nameTranslation.hi',
       'player.fieldTranslations.nameTranslation.bn',
       'player.fieldTranslations.shortNameTranslation.ar',
       'player.fieldTranslations.shortNameTranslation.hi',
       'player.fieldTranslations.shortNameTranslation.bn',
       'statistics.totalPass', 'statistics.accuratePass',
       'statistics.totalLongBalls', 'statistics.accurateLongBalls',
       'statistics.goalAssist', 'statistics.accurateOwnHalfPasses',
       'statistics.totalOwnHalfPasses', 'statistics.totalClearance',
       'statistics.ballRecovery', 'statistics.totalKeeperSweeper',
       'statistics.accurateKeeperSweeper', 'statistics.minutesPlayed',
       'statistics.touches', 'statistics.rating', 'statistics.expectedAssists',
       'statistics.ratingVersions.original',
       'statistics.ratingVersions.alternative', 'statistics.totalShots',
       'player.firstName', 'player.lastName',
       'statistics.accurateOppositionHalfPasses',
       'statistics.totalOppositionHalfPasses', 'statistics.aerialLost',
       'statistics.duelLost', 'statistics.duelWon', 'statistics.totalContest',
       'statistics.wonContest', 'statistics.unsuccessfulTouch',
       'statistics.fouls', 'statistics.possessionLostCtrl', 'captain',
       'statistics.aerialWon', 'statistics.dispossessed',
       'statistics.blockedScoringAttempt', 'statistics.lastManTackle',
       'statistics.totalTackle', 'statistics.wonTackle',
       'statistics.expectedGoals', 'statistics.keyPass',
       'statistics.challengeLost', 'statistics.interceptionWon',
       'statistics.wasFouled', 'statistics.totalCross',
       'statistics.accurateCross', 'statistics.bigChanceCreated',
       'statistics.onTargetScoringAttempt', 'statistics.totalOffside',
       'statistics.expectedGoalsOnTarget', 'statistics.shotOffTarget',
       'statistics.goals', 'side', 'formation'],
      dtype='object')

In [183]:
all_players.columns

Index(['teamId', 'shirtNumber', 'jerseyNumber', 'position', 'substitute',
       'player.name', 'player.slug', 'player.shortName', 'player.position',
       'player.jerseyNumber', 'player.height', 'player.userCount',
       'player.gender', 'player.sofascoreId', 'player.id',
       'player.country.alpha2', 'player.country.alpha3', 'player.country.name',
       'player.country.slug', 'player.marketValueCurrency',
       'player.dateOfBirthTimestamp', 'player.proposedMarketValueRaw.value',
       'player.proposedMarketValueRaw.currency',
       'player.fieldTranslations.nameTranslation.ar',
       'player.fieldTranslations.nameTranslation.hi',
       'player.fieldTranslations.nameTranslation.bn',
       'player.fieldTranslations.shortNameTranslation.ar',
       'player.fieldTranslations.shortNameTranslation.hi',
       'player.fieldTranslations.shortNameTranslation.bn',
       'statistics.totalPass', 'statistics.accuratePass',
       'statistics.totalLongBalls', 'statistics.accurateLongBalls',
       'statistics.goalAssist', 'statistics.accurateOwnHalfPasses',
       'statistics.totalOwnHalfPasses', 'statistics.totalClearance',
       'statistics.ballRecovery', 'statistics.totalKeeperSweeper',
       'statistics.accurateKeeperSweeper', 'statistics.minutesPlayed',
       'statistics.touches', 'statistics.rating', 'statistics.expectedAssists',
       'statistics.ratingVersions.original',
       'statistics.ratingVersions.alternative', 'statistics.totalShots',
       'player.firstName', 'player.lastName',
       'statistics.accurateOppositionHalfPasses',
       'statistics.totalOppositionHalfPasses', 'statistics.aerialLost',
       'statistics.duelLost', 'statistics.duelWon', 'statistics.totalContest',
       'statistics.wonContest', 'statistics.unsuccessfulTouch',
       'statistics.fouls', 'statistics.possessionLostCtrl', 'captain',
       'statistics.aerialWon', 'statistics.dispossessed',
       'statistics.blockedScoringAttempt', 'statistics.lastManTackle',
       'statistics.totalTackle', 'statistics.wonTackle',
       'statistics.expectedGoals', 'statistics.keyPass',
       'statistics.challengeLost', 'statistics.interceptionWon',
       'statistics.wasFouled', 'statistics.totalCross',
       'statistics.accurateCross', 'statistics.bigChanceCreated',
       'statistics.onTargetScoringAttempt', 'statistics.totalOffside',
       'statistics.expectedGoalsOnTarget', 'statistics.shotOffTarget',
       'statistics.goals', 'side', 'formation'],
      dtype='object')

# **Get Last 5 Matches**

In [151]:
my_team_id = df2_flat['id'][0]
my_team_id

np.int64(2829)

In [174]:
last_5 = df_events.tail(5)


last_5 = df_events.sort_values('startTimestamp', ascending=False).head(5)
last_5['opponent'] = last_5.apply(
    lambda row: row['awayTeam.name'] if row['homeTeam.name'] == 'Real Madrid' 
    else row['homeTeam.name'], 
    axis=1
)

last_5[['homeTeam.name', 'awayTeam.name', 'homeScore.current', 'awayScore.current']]

opponents_list = last_5['opponent'].tolist()
print(opponents_list)

['Valencia', 'Barcelona', 'Juventus', 'Getafe', 'Villarreal']

In [175]:
last_5[['homeTeam.name', 'awayTeam.name', 'homeScore.current', 'awayScore.current']]

   homeTeam.name awayTeam.name  homeScore.current  awayScore.current
29   Real Madrid      Valencia                  4                  0
28   Real Madrid     Barcelona                  2                  1
27   Real Madrid      Juventus                  1                  0
26        Getafe   Real Madrid                  0                  1
25   Real Madrid    Villarreal                  3                  1

# **Get top 5 players by rating**

In [172]:
top_rated = home_players.nlargest(5, 'statistics.rating')
# home_players['player.name']
# home_players['player.position']
# home_players['teamId']
# home_players['statistics.minutesPlayed']
print(top_rated[['player.name', 'teamId', 'statistics.rating', 'statistics.minutesPlayed']])

       player.name  teamId  statistics.rating  statistics.minutesPlayed
7          Savinho      17                8.4                      85.0
10   Omar Marmoush      17                8.1                      90.0
8    Jack Grealish      48                7.8                      90.0
4    Nico O'Reilly      17                7.7                      90.0
3   Joško Gvardiol      17                7.6                      89.0

In [185]:
top_rated = away_players.nlargest(5, 'statistics.rating')
# away_players['player.name']
# away_players['player.position']
# away_players['teamId']
# away_players['statistics.minutesPlayed']
print(top_rated[['player.name', 'teamId', 'statistics.rating', 'statistics.minutesPlayed']])

        player.name  teamId  statistics.rating  statistics.minutesPlayed
1         Wout Faes      31                7.1                      90.0
5     Wilfred Ndidi    3050                6.9                      90.0
14  Ricardo Pereira      31                6.9                      14.0
3       Luke Thomas      31                6.7                      90.0
4      James Justin      34                6.7                      90.0

# **Get players with most passes**

In [187]:
top_passers = home_players.nlargest(5, 'statistics.totalPass')
# home_players['statistics.accuratePass']
# home_players['statistics.totalPass']
print(top_passers[['player.name', 'teamId', 'statistics.totalPass', 'statistics.accuratePass']])

      player.name  teamId  statistics.totalPass  statistics.accuratePass
2      Rúben Dias      17                 128.0                    123.0
3  Joško Gvardiol      17                 111.0                    110.0
1   Matheus Nunes      17                 103.0                     97.0
6  İlkay Gündoğan    3061                  96.0                     87.0
4   Nico O'Reilly      17                  73.0                     64.0

In [189]:
top_passers = away_players.nlargest(5, 'statistics.totalPass')
# away_players['statistics.accuratePass']
# away_players['statistics.totalPass']
print(top_passers[['player.name', 'teamId', 'statistics.totalPass', 'statistics.accuratePass']])

      player.name  teamId  statistics.totalPass  statistics.accuratePass
0  Mads Hermansen      37                  40.0                     19.0
2     Conor Coady      64                  33.0                     32.0
1       Wout Faes      31                  32.0                     30.0
3     Luke Thomas      31                  30.0                     26.0
5   Wilfred Ndidi    3050                  27.0                     23.0